/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Infoplus.Client;
using Infoplus.Api;
using Infoplus.Model;

namespace Infoplus.Test
{
    /// <summary>
    ///  Class for testing EdiDocumentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EdiDocumentApiTests
    {
        private EdiDocumentApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EdiDocumentApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EdiDocumentApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EdiDocumentApi
            //Assert.IsInstanceOfType(typeof(EdiDocumentApi), instance, "instance is a EdiDocumentApi");
        }

        
        /// <summary>
        /// Test AddEdiDocument
        /// </summary>
        [Test]
        public void AddEdiDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //EdiDocument body = null;
            //var response = instance.AddEdiDocument(body);
            //Assert.IsInstanceOf<EdiDocument> (response, "response is EdiDocument");
        }
        
        /// <summary>
        /// Test AddEdiDocumentAudit
        /// </summary>
        [Test]
        public void AddEdiDocumentAuditTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ediDocumentId = null;
            //string ediDocumentAudit = null;
            //instance.AddEdiDocumentAudit(ediDocumentId, ediDocumentAudit);
            
        }
        
        /// <summary>
        /// Test AddEdiDocumentFile
        /// </summary>
        [Test]
        public void AddEdiDocumentFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ediDocumentId = null;
            //string fileName = null;
            //instance.AddEdiDocumentFile(ediDocumentId, fileName);
            
        }
        
        /// <summary>
        /// Test AddEdiDocumentTag
        /// </summary>
        [Test]
        public void AddEdiDocumentTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ediDocumentId = null;
            //string ediDocumentTag = null;
            //instance.AddEdiDocumentTag(ediDocumentId, ediDocumentTag);
            
        }
        
        /// <summary>
        /// Test DeleteEdiDocumentTag
        /// </summary>
        [Test]
        public void DeleteEdiDocumentTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ediDocumentId = null;
            //string ediDocumentTag = null;
            //instance.DeleteEdiDocumentTag(ediDocumentId, ediDocumentTag);
            
        }
        
        /// <summary>
        /// Test GetDuplicateEdiDocumentById
        /// </summary>
        [Test]
        public void GetDuplicateEdiDocumentByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ediDocumentId = null;
            //var response = instance.GetDuplicateEdiDocumentById(ediDocumentId);
            //Assert.IsInstanceOf<EdiDocument> (response, "response is EdiDocument");
        }
        
        /// <summary>
        /// Test GetEdiDocumentByFilter
        /// </summary>
        [Test]
        public void GetEdiDocumentByFilterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filter = null;
            //int? page = null;
            //int? limit = null;
            //string sort = null;
            //var response = instance.GetEdiDocumentByFilter(filter, page, limit, sort);
            //Assert.IsInstanceOf<List<EdiDocument>> (response, "response is List<EdiDocument>");
        }
        
        /// <summary>
        /// Test GetEdiDocumentById
        /// </summary>
        [Test]
        public void GetEdiDocumentByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ediDocumentId = null;
            //var response = instance.GetEdiDocumentById(ediDocumentId);
            //Assert.IsInstanceOf<EdiDocument> (response, "response is EdiDocument");
        }
        
        /// <summary>
        /// Test GetEdiDocumentTags
        /// </summary>
        [Test]
        public void GetEdiDocumentTagsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? ediDocumentId = null;
            //instance.GetEdiDocumentTags(ediDocumentId);
            
        }
        
    }

}
