/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Infoplus.Client;
using Infoplus.Api;
using Infoplus.Model;

namespace Infoplus.Test
{
    /// <summary>
    ///  Class for testing OrderSourceStockStatusApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrderSourceStockStatusApiTests
    {
        private OrderSourceStockStatusApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrderSourceStockStatusApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderSourceStockStatusApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrderSourceStockStatusApi
            //Assert.IsInstanceOfType(typeof(OrderSourceStockStatusApi), instance, "instance is a OrderSourceStockStatusApi");
        }

        
        /// <summary>
        /// Test AddOrderSourceStockStatusAudit
        /// </summary>
        [Test]
        public void AddOrderSourceStockStatusAuditTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? orderSourceStockStatusId = null;
            //string orderSourceStockStatusAudit = null;
            //instance.AddOrderSourceStockStatusAudit(orderSourceStockStatusId, orderSourceStockStatusAudit);
            
        }
        
        /// <summary>
        /// Test AddOrderSourceStockStatusTag
        /// </summary>
        [Test]
        public void AddOrderSourceStockStatusTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? orderSourceStockStatusId = null;
            //string orderSourceStockStatusTag = null;
            //instance.AddOrderSourceStockStatusTag(orderSourceStockStatusId, orderSourceStockStatusTag);
            
        }
        
        /// <summary>
        /// Test DeleteOrderSourceStockStatusTag
        /// </summary>
        [Test]
        public void DeleteOrderSourceStockStatusTagTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? orderSourceStockStatusId = null;
            //string orderSourceStockStatusTag = null;
            //instance.DeleteOrderSourceStockStatusTag(orderSourceStockStatusId, orderSourceStockStatusTag);
            
        }
        
        /// <summary>
        /// Test GetDuplicateOrderSourceStockStatusById
        /// </summary>
        [Test]
        public void GetDuplicateOrderSourceStockStatusByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? orderSourceStockStatusId = null;
            //var response = instance.GetDuplicateOrderSourceStockStatusById(orderSourceStockStatusId);
            //Assert.IsInstanceOf<OrderSourceStockStatus> (response, "response is OrderSourceStockStatus");
        }
        
        /// <summary>
        /// Test GetOrderSourceStockStatusByFilter
        /// </summary>
        [Test]
        public void GetOrderSourceStockStatusByFilterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filter = null;
            //int? page = null;
            //int? limit = null;
            //string sort = null;
            //var response = instance.GetOrderSourceStockStatusByFilter(filter, page, limit, sort);
            //Assert.IsInstanceOf<List<OrderSourceStockStatus>> (response, "response is List<OrderSourceStockStatus>");
        }
        
        /// <summary>
        /// Test GetOrderSourceStockStatusById
        /// </summary>
        [Test]
        public void GetOrderSourceStockStatusByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? orderSourceStockStatusId = null;
            //var response = instance.GetOrderSourceStockStatusById(orderSourceStockStatusId);
            //Assert.IsInstanceOf<OrderSourceStockStatus> (response, "response is OrderSourceStockStatus");
        }
        
        /// <summary>
        /// Test GetOrderSourceStockStatusTags
        /// </summary>
        [Test]
        public void GetOrderSourceStockStatusTagsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? orderSourceStockStatusId = null;
            //instance.GetOrderSourceStockStatusTags(orderSourceStockStatusId);
            
        }
        
    }

}
