/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: v1.0
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Infoplus.Client;
using Infoplus.Api;
using Infoplus.Model;

namespace Infoplus.Test
{
    /// <summary>
    ///  Class for testing OverrideReturnAddressApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OverrideReturnAddressApiTests
    {
        private OverrideReturnAddressApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OverrideReturnAddressApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OverrideReturnAddressApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // test 'IsInstanceOfType' OverrideReturnAddressApi
            Assert.IsInstanceOfType(typeof(OverrideReturnAddressApi), instance, "instance is a OverrideReturnAddressApi");
        }

        
        /// <summary>
        /// Test AddOverrideReturnAddress
        /// </summary>
        [Test]
        public void AddOverrideReturnAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OverrideReturnAddress body = null;
            //var response = instance.AddOverrideReturnAddress(body);
            //Assert.IsInstanceOf<OverrideReturnAddress> (response, "response is OverrideReturnAddress");
        }
        
        /// <summary>
        /// Test DeleteOverrideReturnAddress
        /// </summary>
        [Test]
        public void DeleteOverrideReturnAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? overrideReturnAddressId = null;
            //instance.DeleteOverrideReturnAddress(overrideReturnAddressId);
            
        }
        
        /// <summary>
        /// Test GetOverrideReturnAddressByFilter
        /// </summary>
        [Test]
        public void GetOverrideReturnAddressByFilterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filter = null;
            //int? page = null;
            //int? limit = null;
            //string sort = null;
            //var response = instance.GetOverrideReturnAddressByFilter(filter, page, limit, sort);
            //Assert.IsInstanceOf<List<OverrideReturnAddress>> (response, "response is List<OverrideReturnAddress>");
        }
        
        /// <summary>
        /// Test GetOverrideReturnAddressById
        /// </summary>
        [Test]
        public void GetOverrideReturnAddressByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? overrideReturnAddressId = null;
            //var response = instance.GetOverrideReturnAddressById(overrideReturnAddressId);
            //Assert.IsInstanceOf<OverrideReturnAddress> (response, "response is OverrideReturnAddress");
        }
        
        /// <summary>
        /// Test UpdateOverrideReturnAddress
        /// </summary>
        [Test]
        public void UpdateOverrideReturnAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OverrideReturnAddress body = null;
            //instance.UpdateOverrideReturnAddress(body);
            
        }
        
    }

}
