/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Infoplus.Client;
using Infoplus.Api;
using Infoplus.Model;

namespace Infoplus.Test
{
    /// <summary>
    ///  Class for testing PackingSlipTemplateLineExtraDataEnumApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PackingSlipTemplateLineExtraDataEnumApiTests
    {
        private PackingSlipTemplateLineExtraDataEnumApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PackingSlipTemplateLineExtraDataEnumApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PackingSlipTemplateLineExtraDataEnumApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PackingSlipTemplateLineExtraDataEnumApi
            //Assert.IsInstanceOfType(typeof(PackingSlipTemplateLineExtraDataEnumApi), instance, "instance is a PackingSlipTemplateLineExtraDataEnumApi");
        }

        
        /// <summary>
        /// Test GetPackingSlipTemplateLineExtraDataEnumById
        /// </summary>
        [Test]
        public void GetPackingSlipTemplateLineExtraDataEnumByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string packingSlipTemplateLineExtraDataEnumId = null;
            //var response = instance.GetPackingSlipTemplateLineExtraDataEnumById(packingSlipTemplateLineExtraDataEnumId);
            //Assert.IsInstanceOf<PackingSlipTemplateLineExtraDataEnum> (response, "response is PackingSlipTemplateLineExtraDataEnum");
        }
        
        /// <summary>
        /// Test GetPackingSlipTemplateLineExtraDataEnumBySearchText
        /// </summary>
        [Test]
        public void GetPackingSlipTemplateLineExtraDataEnumBySearchTextTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string searchText = null;
            //int? page = null;
            //int? limit = null;
            //var response = instance.GetPackingSlipTemplateLineExtraDataEnumBySearchText(searchText, page, limit);
            //Assert.IsInstanceOf<List<PackingSlipTemplateLineExtraDataEnum>> (response, "response is List<PackingSlipTemplateLineExtraDataEnum>");
        }
        
    }

}
