/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Infoplus.Api;
using Infoplus.Model;
using Infoplus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Infoplus.Test
{
    /// <summary>
    ///  Class for testing CarrierCompanyCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CarrierCompanyCodeTests
    {
        // TODO uncomment below to declare an instance variable for CarrierCompanyCode
        //private CarrierCompanyCode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CarrierCompanyCode
            //instance = new CarrierCompanyCode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarrierCompanyCode
        /// </summary>
        [Test]
        public void CarrierCompanyCodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CarrierCompanyCode
            //Assert.IsInstanceOfType<CarrierCompanyCode> (instance, "variable 'instance' is a CarrierCompanyCode");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'CompanyCode'
        /// </summary>
        [Test]
        public void CompanyCodeTest()
        {
            // TODO unit test for the property 'CompanyCode'
        }

    }

}
