/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Infoplus.Api;
using Infoplus.Model;
using Infoplus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Infoplus.Test
{
    /// <summary>
    ///  Class for testing Item
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemTests
    {
        // TODO uncomment below to declare an instance variable for Item
        //private Item instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Item
            //instance = new Item();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Item
        /// </summary>
        [Test]
        public void ItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Item
            //Assert.IsInstanceOfType<Item> (instance, "variable 'instance' is a Item");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AccountCodeId'
        /// </summary>
        [Test]
        public void AccountCodeIdTest()
        {
            // TODO unit test for the property 'AccountCodeId'
        }
        /// <summary>
        /// Test the property 'LowStockContactId'
        /// </summary>
        [Test]
        public void LowStockContactIdTest()
        {
            // TODO unit test for the property 'LowStockContactId'
        }
        /// <summary>
        /// Test the property 'LegacyLowLevelContactId'
        /// </summary>
        [Test]
        public void LegacyLowLevelContactIdTest()
        {
            // TODO unit test for the property 'LegacyLowLevelContactId'
        }
        /// <summary>
        /// Test the property 'LowStockCodeId'
        /// </summary>
        [Test]
        public void LowStockCodeIdTest()
        {
            // TODO unit test for the property 'LowStockCodeId'
        }
        /// <summary>
        /// Test the property 'MajorGroupId'
        /// </summary>
        [Test]
        public void MajorGroupIdTest()
        {
            // TODO unit test for the property 'MajorGroupId'
        }
        /// <summary>
        /// Test the property 'SubGroupId'
        /// </summary>
        [Test]
        public void SubGroupIdTest()
        {
            // TODO unit test for the property 'SubGroupId'
        }
        /// <summary>
        /// Test the property 'ProductCodeId'
        /// </summary>
        [Test]
        public void ProductCodeIdTest()
        {
            // TODO unit test for the property 'ProductCodeId'
        }
        /// <summary>
        /// Test the property 'SummaryCodeId'
        /// </summary>
        [Test]
        public void SummaryCodeIdTest()
        {
            // TODO unit test for the property 'SummaryCodeId'
        }
        /// <summary>
        /// Test the property 'BuyerId'
        /// </summary>
        [Test]
        public void BuyerIdTest()
        {
            // TODO unit test for the property 'BuyerId'
        }
        /// <summary>
        /// Test the property 'LobId'
        /// </summary>
        [Test]
        public void LobIdTest()
        {
            // TODO unit test for the property 'LobId'
        }
        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Test]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'VendorSKU'
        /// </summary>
        [Test]
        public void VendorSKUTest()
        {
            // TODO unit test for the property 'VendorSKU'
        }
        /// <summary>
        /// Test the property 'Upc'
        /// </summary>
        [Test]
        public void UpcTest()
        {
            // TODO unit test for the property 'Upc'
        }
        /// <summary>
        /// Test the property 'ItemDescription'
        /// </summary>
        [Test]
        public void ItemDescriptionTest()
        {
            // TODO unit test for the property 'ItemDescription'
        }
        /// <summary>
        /// Test the property 'PackingSlipDescription'
        /// </summary>
        [Test]
        public void PackingSlipDescriptionTest()
        {
            // TODO unit test for the property 'PackingSlipDescription'
        }
        /// <summary>
        /// Test the property 'AbsoluteMax'
        /// </summary>
        [Test]
        public void AbsoluteMaxTest()
        {
            // TODO unit test for the property 'AbsoluteMax'
        }
        /// <summary>
        /// Test the property 'AdditionalDescription'
        /// </summary>
        [Test]
        public void AdditionalDescriptionTest()
        {
            // TODO unit test for the property 'AdditionalDescription'
        }
        /// <summary>
        /// Test the property 'Backorder'
        /// </summary>
        [Test]
        public void BackorderTest()
        {
            // TODO unit test for the property 'Backorder'
        }
        /// <summary>
        /// Test the property 'ChargeCode'
        /// </summary>
        [Test]
        public void ChargeCodeTest()
        {
            // TODO unit test for the property 'ChargeCode'
        }
        /// <summary>
        /// Test the property 'CommodityCodeId'
        /// </summary>
        [Test]
        public void CommodityCodeIdTest()
        {
            // TODO unit test for the property 'CommodityCodeId'
        }
        /// <summary>
        /// Test the property 'CompanionCode'
        /// </summary>
        [Test]
        public void CompanionCodeTest()
        {
            // TODO unit test for the property 'CompanionCode'
        }
        /// <summary>
        /// Test the property 'CreateDate'
        /// </summary>
        [Test]
        public void CreateDateTest()
        {
            // TODO unit test for the property 'CreateDate'
        }
        /// <summary>
        /// Test the property 'CriticalAmount'
        /// </summary>
        [Test]
        public void CriticalAmountTest()
        {
            // TODO unit test for the property 'CriticalAmount'
        }
        /// <summary>
        /// Test the property 'OverallFixedReorderPoint'
        /// </summary>
        [Test]
        public void OverallFixedReorderPointTest()
        {
            // TODO unit test for the property 'OverallFixedReorderPoint'
        }
        /// <summary>
        /// Test the property 'OverallLeadTime'
        /// </summary>
        [Test]
        public void OverallLeadTimeTest()
        {
            // TODO unit test for the property 'OverallLeadTime'
        }
        /// <summary>
        /// Test the property 'SellPrice'
        /// </summary>
        [Test]
        public void SellPriceTest()
        {
            // TODO unit test for the property 'SellPrice'
        }
        /// <summary>
        /// Test the property 'PricingPer'
        /// </summary>
        [Test]
        public void PricingPerTest()
        {
            // TODO unit test for the property 'PricingPer'
        }
        /// <summary>
        /// Test the property 'LotControlFlag'
        /// </summary>
        [Test]
        public void LotControlFlagTest()
        {
            // TODO unit test for the property 'LotControlFlag'
        }
        /// <summary>
        /// Test the property 'MaxCycle'
        /// </summary>
        [Test]
        public void MaxCycleTest()
        {
            // TODO unit test for the property 'MaxCycle'
        }
        /// <summary>
        /// Test the property 'MaxInterim'
        /// </summary>
        [Test]
        public void MaxInterimTest()
        {
            // TODO unit test for the property 'MaxInterim'
        }
        /// <summary>
        /// Test the property 'NumericSortOrder'
        /// </summary>
        [Test]
        public void NumericSortOrderTest()
        {
            // TODO unit test for the property 'NumericSortOrder'
        }
        /// <summary>
        /// Test the property 'OutsideVendorId'
        /// </summary>
        [Test]
        public void OutsideVendorIdTest()
        {
            // TODO unit test for the property 'OutsideVendorId'
        }
        /// <summary>
        /// Test the property 'PickCode'
        /// </summary>
        [Test]
        public void PickCodeTest()
        {
            // TODO unit test for the property 'PickCode'
        }
        /// <summary>
        /// Test the property 'PodOrderSuffix'
        /// </summary>
        [Test]
        public void PodOrderSuffixTest()
        {
            // TODO unit test for the property 'PodOrderSuffix'
        }
        /// <summary>
        /// Test the property 'PodRevDate'
        /// </summary>
        [Test]
        public void PodRevDateTest()
        {
            // TODO unit test for the property 'PodRevDate'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SeasonalItem'
        /// </summary>
        [Test]
        public void SeasonalItemTest()
        {
            // TODO unit test for the property 'SeasonalItem'
        }
        /// <summary>
        /// Test the property 'RequiresProductionLot'
        /// </summary>
        [Test]
        public void RequiresProductionLotTest()
        {
            // TODO unit test for the property 'RequiresProductionLot'
        }
        /// <summary>
        /// Test the property 'Sector'
        /// </summary>
        [Test]
        public void SectorTest()
        {
            // TODO unit test for the property 'Sector'
        }
        /// <summary>
        /// Test the property 'Secure'
        /// </summary>
        [Test]
        public void SecureTest()
        {
            // TODO unit test for the property 'Secure'
        }
        /// <summary>
        /// Test the property 'SerialCode'
        /// </summary>
        [Test]
        public void SerialCodeTest()
        {
            // TODO unit test for the property 'SerialCode'
        }
        /// <summary>
        /// Test the property 'UnitCode'
        /// </summary>
        [Test]
        public void UnitCodeTest()
        {
            // TODO unit test for the property 'UnitCode'
        }
        /// <summary>
        /// Test the property 'UnitsPerWrap'
        /// </summary>
        [Test]
        public void UnitsPerWrapTest()
        {
            // TODO unit test for the property 'UnitsPerWrap'
        }
        /// <summary>
        /// Test the property 'WeightPerWrap'
        /// </summary>
        [Test]
        public void WeightPerWrapTest()
        {
            // TODO unit test for the property 'WeightPerWrap'
        }
        /// <summary>
        /// Test the property 'QuantityPerInnerPack'
        /// </summary>
        [Test]
        public void QuantityPerInnerPackTest()
        {
            // TODO unit test for the property 'QuantityPerInnerPack'
        }
        /// <summary>
        /// Test the property 'QuantityPerCase'
        /// </summary>
        [Test]
        public void QuantityPerCaseTest()
        {
            // TODO unit test for the property 'QuantityPerCase'
        }
        /// <summary>
        /// Test the property 'QuantityPerPallet'
        /// </summary>
        [Test]
        public void QuantityPerPalletTest()
        {
            // TODO unit test for the property 'QuantityPerPallet'
        }
        /// <summary>
        /// Test the property 'InnerPackBarcode'
        /// </summary>
        [Test]
        public void InnerPackBarcodeTest()
        {
            // TODO unit test for the property 'InnerPackBarcode'
        }
        /// <summary>
        /// Test the property 'CaseBarcode'
        /// </summary>
        [Test]
        public void CaseBarcodeTest()
        {
            // TODO unit test for the property 'CaseBarcode'
        }
        /// <summary>
        /// Test the property 'PalletBarcode'
        /// </summary>
        [Test]
        public void PalletBarcodeTest()
        {
            // TODO unit test for the property 'PalletBarcode'
        }
        /// <summary>
        /// Test the property 'VoidDate'
        /// </summary>
        [Test]
        public void VoidDateTest()
        {
            // TODO unit test for the property 'VoidDate'
        }
        /// <summary>
        /// Test the property 'WrapCode'
        /// </summary>
        [Test]
        public void WrapCodeTest()
        {
            // TODO unit test for the property 'WrapCode'
        }
        /// <summary>
        /// Test the property 'ExtrinsicText1'
        /// </summary>
        [Test]
        public void ExtrinsicText1Test()
        {
            // TODO unit test for the property 'ExtrinsicText1'
        }
        /// <summary>
        /// Test the property 'ExtrinsicText2'
        /// </summary>
        [Test]
        public void ExtrinsicText2Test()
        {
            // TODO unit test for the property 'ExtrinsicText2'
        }
        /// <summary>
        /// Test the property 'ExtrinsicText3'
        /// </summary>
        [Test]
        public void ExtrinsicText3Test()
        {
            // TODO unit test for the property 'ExtrinsicText3'
        }
        /// <summary>
        /// Test the property 'ExtrinsicNumber1'
        /// </summary>
        [Test]
        public void ExtrinsicNumber1Test()
        {
            // TODO unit test for the property 'ExtrinsicNumber1'
        }
        /// <summary>
        /// Test the property 'ExtrinsicNumber2'
        /// </summary>
        [Test]
        public void ExtrinsicNumber2Test()
        {
            // TODO unit test for the property 'ExtrinsicNumber2'
        }
        /// <summary>
        /// Test the property 'ExtrinsicDecimal1'
        /// </summary>
        [Test]
        public void ExtrinsicDecimal1Test()
        {
            // TODO unit test for the property 'ExtrinsicDecimal1'
        }
        /// <summary>
        /// Test the property 'ExtrinsicDecimal2'
        /// </summary>
        [Test]
        public void ExtrinsicDecimal2Test()
        {
            // TODO unit test for the property 'ExtrinsicDecimal2'
        }
        /// <summary>
        /// Test the property 'CasebreakEnabled'
        /// </summary>
        [Test]
        public void CasebreakEnabledTest()
        {
            // TODO unit test for the property 'CasebreakEnabled'
        }
        /// <summary>
        /// Test the property 'VendorId'
        /// </summary>
        [Test]
        public void VendorIdTest()
        {
            // TODO unit test for the property 'VendorId'
        }
        /// <summary>
        /// Test the property 'VendorPrice'
        /// </summary>
        [Test]
        public void VendorPriceTest()
        {
            // TODO unit test for the property 'VendorPrice'
        }
        /// <summary>
        /// Test the property 'VendorPer'
        /// </summary>
        [Test]
        public void VendorPerTest()
        {
            // TODO unit test for the property 'VendorPer'
        }
        /// <summary>
        /// Test the property 'ModifyDate'
        /// </summary>
        [Test]
        public void ModifyDateTest()
        {
            // TODO unit test for the property 'ModifyDate'
        }
        /// <summary>
        /// Test the property 'PrimaryImage'
        /// </summary>
        [Test]
        public void PrimaryImageTest()
        {
            // TODO unit test for the property 'PrimaryImage'
        }
        /// <summary>
        /// Test the property 'PickImage'
        /// </summary>
        [Test]
        public void PickImageTest()
        {
            // TODO unit test for the property 'PickImage'
        }
        /// <summary>
        /// Test the property 'BehaviorType'
        /// </summary>
        [Test]
        public void BehaviorTypeTest()
        {
            // TODO unit test for the property 'BehaviorType'
        }
        /// <summary>
        /// Test the property 'AssemblyInstructions'
        /// </summary>
        [Test]
        public void AssemblyInstructionsTest()
        {
            // TODO unit test for the property 'AssemblyInstructions'
        }
        /// <summary>
        /// Test the property 'ForwardLotMixingRule'
        /// </summary>
        [Test]
        public void ForwardLotMixingRuleTest()
        {
            // TODO unit test for the property 'ForwardLotMixingRule'
        }
        /// <summary>
        /// Test the property 'StorageLotMixingRule'
        /// </summary>
        [Test]
        public void StorageLotMixingRuleTest()
        {
            // TODO unit test for the property 'StorageLotMixingRule'
        }
        /// <summary>
        /// Test the property 'ForwardItemMixingRule'
        /// </summary>
        [Test]
        public void ForwardItemMixingRuleTest()
        {
            // TODO unit test for the property 'ForwardItemMixingRule'
        }
        /// <summary>
        /// Test the property 'StorageItemMixingRule'
        /// </summary>
        [Test]
        public void StorageItemMixingRuleTest()
        {
            // TODO unit test for the property 'StorageItemMixingRule'
        }
        /// <summary>
        /// Test the property 'AllocationRule'
        /// </summary>
        [Test]
        public void AllocationRuleTest()
        {
            // TODO unit test for the property 'AllocationRule'
        }
        /// <summary>
        /// Test the property 'AllocationSort'
        /// </summary>
        [Test]
        public void AllocationSortTest()
        {
            // TODO unit test for the property 'AllocationSort'
        }
        /// <summary>
        /// Test the property 'AllocationField'
        /// </summary>
        [Test]
        public void AllocationFieldTest()
        {
            // TODO unit test for the property 'AllocationField'
        }
        /// <summary>
        /// Test the property 'BarcodeField'
        /// </summary>
        [Test]
        public void BarcodeFieldTest()
        {
            // TODO unit test for the property 'BarcodeField'
        }
        /// <summary>
        /// Test the property 'WarehouseDisplayField'
        /// </summary>
        [Test]
        public void WarehouseDisplayFieldTest()
        {
            // TODO unit test for the property 'WarehouseDisplayField'
        }
        /// <summary>
        /// Test the property 'ProductIdTagSchemeId'
        /// </summary>
        [Test]
        public void ProductIdTagSchemeIdTest()
        {
            // TODO unit test for the property 'ProductIdTagSchemeId'
        }
        /// <summary>
        /// Test the property 'ItemSerialSchemeId'
        /// </summary>
        [Test]
        public void ItemSerialSchemeIdTest()
        {
            // TODO unit test for the property 'ItemSerialSchemeId'
        }
        /// <summary>
        /// Test the property 'ReceivingCriteriaSchemeId'
        /// </summary>
        [Test]
        public void ReceivingCriteriaSchemeIdTest()
        {
            // TODO unit test for the property 'ReceivingCriteriaSchemeId'
        }
        /// <summary>
        /// Test the property 'AsnRule'
        /// </summary>
        [Test]
        public void AsnRuleTest()
        {
            // TODO unit test for the property 'AsnRule'
        }
        /// <summary>
        /// Test the property 'QuantityType'
        /// </summary>
        [Test]
        public void QuantityTypeTest()
        {
            // TODO unit test for the property 'QuantityType'
        }
        /// <summary>
        /// Test the property 'Hazmat'
        /// </summary>
        [Test]
        public void HazmatTest()
        {
            // TODO unit test for the property 'Hazmat'
        }
        /// <summary>
        /// Test the property 'IsAlcohol'
        /// </summary>
        [Test]
        public void IsAlcoholTest()
        {
            // TODO unit test for the property 'IsAlcohol'
        }
        /// <summary>
        /// Test the property 'AlcoholType'
        /// </summary>
        [Test]
        public void AlcoholTypeTest()
        {
            // TODO unit test for the property 'AlcoholType'
        }
        /// <summary>
        /// Test the property 'AlcoholContent'
        /// </summary>
        [Test]
        public void AlcoholContentTest()
        {
            // TODO unit test for the property 'AlcoholContent'
        }
        /// <summary>
        /// Test the property 'AlcoholContainer'
        /// </summary>
        [Test]
        public void AlcoholContainerTest()
        {
            // TODO unit test for the property 'AlcoholContainer'
        }
        /// <summary>
        /// Test the property 'AlcoholVintageYear'
        /// </summary>
        [Test]
        public void AlcoholVintageYearTest()
        {
            // TODO unit test for the property 'AlcoholVintageYear'
        }
        /// <summary>
        /// Test the property 'AlcoholCountry'
        /// </summary>
        [Test]
        public void AlcoholCountryTest()
        {
            // TODO unit test for the property 'AlcoholCountry'
        }
        /// <summary>
        /// Test the property 'AlcoholState'
        /// </summary>
        [Test]
        public void AlcoholStateTest()
        {
            // TODO unit test for the property 'AlcoholState'
        }
        /// <summary>
        /// Test the property 'AlcoholRegion'
        /// </summary>
        [Test]
        public void AlcoholRegionTest()
        {
            // TODO unit test for the property 'AlcoholRegion'
        }
        /// <summary>
        /// Test the property 'AlcoholBrand'
        /// </summary>
        [Test]
        public void AlcoholBrandTest()
        {
            // TODO unit test for the property 'AlcoholBrand'
        }
        /// <summary>
        /// Test the property 'AlcoholUPCCode'
        /// </summary>
        [Test]
        public void AlcoholUPCCodeTest()
        {
            // TODO unit test for the property 'AlcoholUPCCode'
        }
        /// <summary>
        /// Test the property 'AlcoholNAMBCACode'
        /// </summary>
        [Test]
        public void AlcoholNAMBCACodeTest()
        {
            // TODO unit test for the property 'AlcoholNAMBCACode'
        }
        /// <summary>
        /// Test the property 'AlcoholUNIMERCCode'
        /// </summary>
        [Test]
        public void AlcoholUNIMERCCodeTest()
        {
            // TODO unit test for the property 'AlcoholUNIMERCCode'
        }
        /// <summary>
        /// Test the property 'AlcoholSCCCode'
        /// </summary>
        [Test]
        public void AlcoholSCCCodeTest()
        {
            // TODO unit test for the property 'AlcoholSCCCode'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'TopUp'
        /// </summary>
        [Test]
        public void TopUpTest()
        {
            // TODO unit test for the property 'TopUp'
        }
        /// <summary>
        /// Test the property 'ShipSolo'
        /// </summary>
        [Test]
        public void ShipSoloTest()
        {
            // TODO unit test for the property 'ShipSolo'
        }
        /// <summary>
        /// Test the property 'InventoryUpdateTimestamp'
        /// </summary>
        [Test]
        public void InventoryUpdateTimestampTest()
        {
            // TODO unit test for the property 'InventoryUpdateTimestamp'
        }
        /// <summary>
        /// Test the property 'AvailableQuantity'
        /// </summary>
        [Test]
        public void AvailableQuantityTest()
        {
            // TODO unit test for the property 'AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'DamagedQuantity'
        /// </summary>
        [Test]
        public void DamagedQuantityTest()
        {
            // TODO unit test for the property 'DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'OnHandQuantity'
        /// </summary>
        [Test]
        public void OnHandQuantityTest()
        {
            // TODO unit test for the property 'OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'OpenOrderQuantity'
        /// </summary>
        [Test]
        public void OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'OpenPOQuantity'
        /// </summary>
        [Test]
        public void OpenPOQuantityTest()
        {
            // TODO unit test for the property 'OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'OrderableQuantity'
        /// </summary>
        [Test]
        public void OrderableQuantityTest()
        {
            // TODO unit test for the property 'OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'UnallocatableQuantity'
        /// </summary>
        [Test]
        public void UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'UnavailableQuantity'
        /// </summary>
        [Test]
        public void UnavailableQuantityTest()
        {
            // TODO unit test for the property 'UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'TotalDemand'
        /// </summary>
        [Test]
        public void TotalDemandTest()
        {
            // TODO unit test for the property 'TotalDemand'
        }
        /// <summary>
        /// Test the property 'AvailableQuantityInnerPacks'
        /// </summary>
        [Test]
        public void AvailableQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'AvailableQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'DamagedQuantityInnerPacks'
        /// </summary>
        [Test]
        public void DamagedQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'DamagedQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'InFulfillmentProcessQuantityInnerPacks'
        /// </summary>
        [Test]
        public void InFulfillmentProcessQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'InFulfillmentProcessQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'OnHandQuantityInnerPacks'
        /// </summary>
        [Test]
        public void OnHandQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'OnHandQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'OpenOrderQuantityInnerPacks'
        /// </summary>
        [Test]
        public void OpenOrderQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'OpenOrderQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'OpenPOQuantityInnerPacks'
        /// </summary>
        [Test]
        public void OpenPOQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'OpenPOQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'OrderableQuantityInnerPacks'
        /// </summary>
        [Test]
        public void OrderableQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'OrderableQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'UnallocatableQuantityInnerPacks'
        /// </summary>
        [Test]
        public void UnallocatableQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'UnallocatableQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'UnavailableQuantityInnerPacks'
        /// </summary>
        [Test]
        public void UnavailableQuantityInnerPacksTest()
        {
            // TODO unit test for the property 'UnavailableQuantityInnerPacks'
        }
        /// <summary>
        /// Test the property 'AvailableQuantityCases'
        /// </summary>
        [Test]
        public void AvailableQuantityCasesTest()
        {
            // TODO unit test for the property 'AvailableQuantityCases'
        }
        /// <summary>
        /// Test the property 'DamagedQuantityCases'
        /// </summary>
        [Test]
        public void DamagedQuantityCasesTest()
        {
            // TODO unit test for the property 'DamagedQuantityCases'
        }
        /// <summary>
        /// Test the property 'InFulfillmentProcessQuantityCases'
        /// </summary>
        [Test]
        public void InFulfillmentProcessQuantityCasesTest()
        {
            // TODO unit test for the property 'InFulfillmentProcessQuantityCases'
        }
        /// <summary>
        /// Test the property 'OnHandQuantityCases'
        /// </summary>
        [Test]
        public void OnHandQuantityCasesTest()
        {
            // TODO unit test for the property 'OnHandQuantityCases'
        }
        /// <summary>
        /// Test the property 'OpenOrderQuantityCases'
        /// </summary>
        [Test]
        public void OpenOrderQuantityCasesTest()
        {
            // TODO unit test for the property 'OpenOrderQuantityCases'
        }
        /// <summary>
        /// Test the property 'OpenPOQuantityCases'
        /// </summary>
        [Test]
        public void OpenPOQuantityCasesTest()
        {
            // TODO unit test for the property 'OpenPOQuantityCases'
        }
        /// <summary>
        /// Test the property 'OrderableQuantityCases'
        /// </summary>
        [Test]
        public void OrderableQuantityCasesTest()
        {
            // TODO unit test for the property 'OrderableQuantityCases'
        }
        /// <summary>
        /// Test the property 'UnallocatableQuantityCases'
        /// </summary>
        [Test]
        public void UnallocatableQuantityCasesTest()
        {
            // TODO unit test for the property 'UnallocatableQuantityCases'
        }
        /// <summary>
        /// Test the property 'UnavailableQuantityCases'
        /// </summary>
        [Test]
        public void UnavailableQuantityCasesTest()
        {
            // TODO unit test for the property 'UnavailableQuantityCases'
        }
        /// <summary>
        /// Test the property 'AvailableQuantityPallets'
        /// </summary>
        [Test]
        public void AvailableQuantityPalletsTest()
        {
            // TODO unit test for the property 'AvailableQuantityPallets'
        }
        /// <summary>
        /// Test the property 'DamagedQuantityPallets'
        /// </summary>
        [Test]
        public void DamagedQuantityPalletsTest()
        {
            // TODO unit test for the property 'DamagedQuantityPallets'
        }
        /// <summary>
        /// Test the property 'InFulfillmentProcessQuantityPallets'
        /// </summary>
        [Test]
        public void InFulfillmentProcessQuantityPalletsTest()
        {
            // TODO unit test for the property 'InFulfillmentProcessQuantityPallets'
        }
        /// <summary>
        /// Test the property 'OnHandQuantityPallets'
        /// </summary>
        [Test]
        public void OnHandQuantityPalletsTest()
        {
            // TODO unit test for the property 'OnHandQuantityPallets'
        }
        /// <summary>
        /// Test the property 'OpenOrderQuantityPallets'
        /// </summary>
        [Test]
        public void OpenOrderQuantityPalletsTest()
        {
            // TODO unit test for the property 'OpenOrderQuantityPallets'
        }
        /// <summary>
        /// Test the property 'OpenPOQuantityPallets'
        /// </summary>
        [Test]
        public void OpenPOQuantityPalletsTest()
        {
            // TODO unit test for the property 'OpenPOQuantityPallets'
        }
        /// <summary>
        /// Test the property 'OrderableQuantityPallets'
        /// </summary>
        [Test]
        public void OrderableQuantityPalletsTest()
        {
            // TODO unit test for the property 'OrderableQuantityPallets'
        }
        /// <summary>
        /// Test the property 'UnallocatableQuantityPallets'
        /// </summary>
        [Test]
        public void UnallocatableQuantityPalletsTest()
        {
            // TODO unit test for the property 'UnallocatableQuantityPallets'
        }
        /// <summary>
        /// Test the property 'UnavailableQuantityPallets'
        /// </summary>
        [Test]
        public void UnavailableQuantityPalletsTest()
        {
            // TODO unit test for the property 'UnavailableQuantityPallets'
        }
        /// <summary>
        /// Test the property 'OverallDaysOnHand'
        /// </summary>
        [Test]
        public void OverallDaysOnHandTest()
        {
            // TODO unit test for the property 'OverallDaysOnHand'
        }
        /// <summary>
        /// Test the property 'OverallStockStatus'
        /// </summary>
        [Test]
        public void OverallStockStatusTest()
        {
            // TODO unit test for the property 'OverallStockStatus'
        }
        /// <summary>
        /// Test the property 'EstimatedPallets'
        /// </summary>
        [Test]
        public void EstimatedPalletsTest()
        {
            // TODO unit test for the property 'EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'EstimatedCases'
        /// </summary>
        [Test]
        public void EstimatedCasesTest()
        {
            // TODO unit test for the property 'EstimatedCases'
        }
        /// <summary>
        /// Test the property 'EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse1Id'
        /// </summary>
        [Test]
        public void Warehouse1IdTest()
        {
            // TODO unit test for the property 'Warehouse1Id'
        }
        /// <summary>
        /// Test the property 'W1AvailableQuantity'
        /// </summary>
        [Test]
        public void W1AvailableQuantityTest()
        {
            // TODO unit test for the property 'W1AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W1DamagedQuantity'
        /// </summary>
        [Test]
        public void W1DamagedQuantityTest()
        {
            // TODO unit test for the property 'W1DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W1InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W1InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W1InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W1OnHandQuantity'
        /// </summary>
        [Test]
        public void W1OnHandQuantityTest()
        {
            // TODO unit test for the property 'W1OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W1OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W1OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W1OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W1OpenPOQuantity'
        /// </summary>
        [Test]
        public void W1OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W1OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W1OrderableQuantity'
        /// </summary>
        [Test]
        public void W1OrderableQuantityTest()
        {
            // TODO unit test for the property 'W1OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W1UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W1UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W1UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W1UnavailableQuantity'
        /// </summary>
        [Test]
        public void W1UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W1UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W1DaysOnHand'
        /// </summary>
        [Test]
        public void W1DaysOnHandTest()
        {
            // TODO unit test for the property 'W1DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W1StockStatus'
        /// </summary>
        [Test]
        public void W1StockStatusTest()
        {
            // TODO unit test for the property 'W1StockStatus'
        }
        /// <summary>
        /// Test the property 'W1EstimatedPallets'
        /// </summary>
        [Test]
        public void W1EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W1EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W1EstimatedCases'
        /// </summary>
        [Test]
        public void W1EstimatedCasesTest()
        {
            // TODO unit test for the property 'W1EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W1EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W1EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W1EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W1NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W1NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W1NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse2Id'
        /// </summary>
        [Test]
        public void Warehouse2IdTest()
        {
            // TODO unit test for the property 'Warehouse2Id'
        }
        /// <summary>
        /// Test the property 'W2AvailableQuantity'
        /// </summary>
        [Test]
        public void W2AvailableQuantityTest()
        {
            // TODO unit test for the property 'W2AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W2DamagedQuantity'
        /// </summary>
        [Test]
        public void W2DamagedQuantityTest()
        {
            // TODO unit test for the property 'W2DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W2InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W2InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W2InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W2OnHandQuantity'
        /// </summary>
        [Test]
        public void W2OnHandQuantityTest()
        {
            // TODO unit test for the property 'W2OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W2OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W2OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W2OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W2OpenPOQuantity'
        /// </summary>
        [Test]
        public void W2OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W2OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W2OrderableQuantity'
        /// </summary>
        [Test]
        public void W2OrderableQuantityTest()
        {
            // TODO unit test for the property 'W2OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W2UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W2UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W2UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W2UnavailableQuantity'
        /// </summary>
        [Test]
        public void W2UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W2UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W2DaysOnHand'
        /// </summary>
        [Test]
        public void W2DaysOnHandTest()
        {
            // TODO unit test for the property 'W2DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W2StockStatus'
        /// </summary>
        [Test]
        public void W2StockStatusTest()
        {
            // TODO unit test for the property 'W2StockStatus'
        }
        /// <summary>
        /// Test the property 'W2EstimatedPallets'
        /// </summary>
        [Test]
        public void W2EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W2EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W2EstimatedCases'
        /// </summary>
        [Test]
        public void W2EstimatedCasesTest()
        {
            // TODO unit test for the property 'W2EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W2EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W2EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W2EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W2NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W2NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W2NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse3Id'
        /// </summary>
        [Test]
        public void Warehouse3IdTest()
        {
            // TODO unit test for the property 'Warehouse3Id'
        }
        /// <summary>
        /// Test the property 'W3AvailableQuantity'
        /// </summary>
        [Test]
        public void W3AvailableQuantityTest()
        {
            // TODO unit test for the property 'W3AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W3DamagedQuantity'
        /// </summary>
        [Test]
        public void W3DamagedQuantityTest()
        {
            // TODO unit test for the property 'W3DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W3InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W3InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W3InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W3OnHandQuantity'
        /// </summary>
        [Test]
        public void W3OnHandQuantityTest()
        {
            // TODO unit test for the property 'W3OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W3OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W3OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W3OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W3OpenPOQuantity'
        /// </summary>
        [Test]
        public void W3OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W3OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W3OrderableQuantity'
        /// </summary>
        [Test]
        public void W3OrderableQuantityTest()
        {
            // TODO unit test for the property 'W3OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W3UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W3UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W3UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W3UnavailableQuantity'
        /// </summary>
        [Test]
        public void W3UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W3UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W3DaysOnHand'
        /// </summary>
        [Test]
        public void W3DaysOnHandTest()
        {
            // TODO unit test for the property 'W3DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W3StockStatus'
        /// </summary>
        [Test]
        public void W3StockStatusTest()
        {
            // TODO unit test for the property 'W3StockStatus'
        }
        /// <summary>
        /// Test the property 'W3EstimatedPallets'
        /// </summary>
        [Test]
        public void W3EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W3EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W3EstimatedCases'
        /// </summary>
        [Test]
        public void W3EstimatedCasesTest()
        {
            // TODO unit test for the property 'W3EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W3EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W3EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W3EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W3NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W3NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W3NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse4Id'
        /// </summary>
        [Test]
        public void Warehouse4IdTest()
        {
            // TODO unit test for the property 'Warehouse4Id'
        }
        /// <summary>
        /// Test the property 'W4AvailableQuantity'
        /// </summary>
        [Test]
        public void W4AvailableQuantityTest()
        {
            // TODO unit test for the property 'W4AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W4DamagedQuantity'
        /// </summary>
        [Test]
        public void W4DamagedQuantityTest()
        {
            // TODO unit test for the property 'W4DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W4InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W4InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W4InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W4OnHandQuantity'
        /// </summary>
        [Test]
        public void W4OnHandQuantityTest()
        {
            // TODO unit test for the property 'W4OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W4OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W4OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W4OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W4OpenPOQuantity'
        /// </summary>
        [Test]
        public void W4OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W4OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W4OrderableQuantity'
        /// </summary>
        [Test]
        public void W4OrderableQuantityTest()
        {
            // TODO unit test for the property 'W4OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W4UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W4UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W4UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W4UnavailableQuantity'
        /// </summary>
        [Test]
        public void W4UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W4UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W4DaysOnHand'
        /// </summary>
        [Test]
        public void W4DaysOnHandTest()
        {
            // TODO unit test for the property 'W4DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W4StockStatus'
        /// </summary>
        [Test]
        public void W4StockStatusTest()
        {
            // TODO unit test for the property 'W4StockStatus'
        }
        /// <summary>
        /// Test the property 'W4EstimatedPallets'
        /// </summary>
        [Test]
        public void W4EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W4EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W4EstimatedCases'
        /// </summary>
        [Test]
        public void W4EstimatedCasesTest()
        {
            // TODO unit test for the property 'W4EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W4EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W4EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W4EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W4NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W4NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W4NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse5Id'
        /// </summary>
        [Test]
        public void Warehouse5IdTest()
        {
            // TODO unit test for the property 'Warehouse5Id'
        }
        /// <summary>
        /// Test the property 'W5AvailableQuantity'
        /// </summary>
        [Test]
        public void W5AvailableQuantityTest()
        {
            // TODO unit test for the property 'W5AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W5DamagedQuantity'
        /// </summary>
        [Test]
        public void W5DamagedQuantityTest()
        {
            // TODO unit test for the property 'W5DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W5InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W5InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W5InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W5OnHandQuantity'
        /// </summary>
        [Test]
        public void W5OnHandQuantityTest()
        {
            // TODO unit test for the property 'W5OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W5OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W5OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W5OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W5OpenPOQuantity'
        /// </summary>
        [Test]
        public void W5OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W5OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W5OrderableQuantity'
        /// </summary>
        [Test]
        public void W5OrderableQuantityTest()
        {
            // TODO unit test for the property 'W5OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W5UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W5UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W5UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W5UnavailableQuantity'
        /// </summary>
        [Test]
        public void W5UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W5UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W5DaysOnHand'
        /// </summary>
        [Test]
        public void W5DaysOnHandTest()
        {
            // TODO unit test for the property 'W5DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W5StockStatus'
        /// </summary>
        [Test]
        public void W5StockStatusTest()
        {
            // TODO unit test for the property 'W5StockStatus'
        }
        /// <summary>
        /// Test the property 'W5EstimatedPallets'
        /// </summary>
        [Test]
        public void W5EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W5EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W5EstimatedCases'
        /// </summary>
        [Test]
        public void W5EstimatedCasesTest()
        {
            // TODO unit test for the property 'W5EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W5EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W5EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W5EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W5NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W5NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W5NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse6Id'
        /// </summary>
        [Test]
        public void Warehouse6IdTest()
        {
            // TODO unit test for the property 'Warehouse6Id'
        }
        /// <summary>
        /// Test the property 'W6AvailableQuantity'
        /// </summary>
        [Test]
        public void W6AvailableQuantityTest()
        {
            // TODO unit test for the property 'W6AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W6DamagedQuantity'
        /// </summary>
        [Test]
        public void W6DamagedQuantityTest()
        {
            // TODO unit test for the property 'W6DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W6InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W6InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W6InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W6OnHandQuantity'
        /// </summary>
        [Test]
        public void W6OnHandQuantityTest()
        {
            // TODO unit test for the property 'W6OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W6OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W6OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W6OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W6OpenPOQuantity'
        /// </summary>
        [Test]
        public void W6OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W6OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W6OrderableQuantity'
        /// </summary>
        [Test]
        public void W6OrderableQuantityTest()
        {
            // TODO unit test for the property 'W6OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W6UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W6UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W6UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W6UnavailableQuantity'
        /// </summary>
        [Test]
        public void W6UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W6UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W6DaysOnHand'
        /// </summary>
        [Test]
        public void W6DaysOnHandTest()
        {
            // TODO unit test for the property 'W6DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W6StockStatus'
        /// </summary>
        [Test]
        public void W6StockStatusTest()
        {
            // TODO unit test for the property 'W6StockStatus'
        }
        /// <summary>
        /// Test the property 'W6EstimatedPallets'
        /// </summary>
        [Test]
        public void W6EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W6EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W6EstimatedCases'
        /// </summary>
        [Test]
        public void W6EstimatedCasesTest()
        {
            // TODO unit test for the property 'W6EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W6EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W6EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W6EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W6NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W6NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W6NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse7Id'
        /// </summary>
        [Test]
        public void Warehouse7IdTest()
        {
            // TODO unit test for the property 'Warehouse7Id'
        }
        /// <summary>
        /// Test the property 'W7AvailableQuantity'
        /// </summary>
        [Test]
        public void W7AvailableQuantityTest()
        {
            // TODO unit test for the property 'W7AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W7DamagedQuantity'
        /// </summary>
        [Test]
        public void W7DamagedQuantityTest()
        {
            // TODO unit test for the property 'W7DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W7InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W7InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W7InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W7OnHandQuantity'
        /// </summary>
        [Test]
        public void W7OnHandQuantityTest()
        {
            // TODO unit test for the property 'W7OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W7OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W7OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W7OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W7OpenPOQuantity'
        /// </summary>
        [Test]
        public void W7OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W7OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W7OrderableQuantity'
        /// </summary>
        [Test]
        public void W7OrderableQuantityTest()
        {
            // TODO unit test for the property 'W7OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W7UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W7UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W7UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W7UnavailableQuantity'
        /// </summary>
        [Test]
        public void W7UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W7UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W7DaysOnHand'
        /// </summary>
        [Test]
        public void W7DaysOnHandTest()
        {
            // TODO unit test for the property 'W7DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W7StockStatus'
        /// </summary>
        [Test]
        public void W7StockStatusTest()
        {
            // TODO unit test for the property 'W7StockStatus'
        }
        /// <summary>
        /// Test the property 'W7EstimatedPallets'
        /// </summary>
        [Test]
        public void W7EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W7EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W7EstimatedCases'
        /// </summary>
        [Test]
        public void W7EstimatedCasesTest()
        {
            // TODO unit test for the property 'W7EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W7EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W7EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W7EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W7NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W7NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W7NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse8Id'
        /// </summary>
        [Test]
        public void Warehouse8IdTest()
        {
            // TODO unit test for the property 'Warehouse8Id'
        }
        /// <summary>
        /// Test the property 'W8AvailableQuantity'
        /// </summary>
        [Test]
        public void W8AvailableQuantityTest()
        {
            // TODO unit test for the property 'W8AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W8DamagedQuantity'
        /// </summary>
        [Test]
        public void W8DamagedQuantityTest()
        {
            // TODO unit test for the property 'W8DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W8InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W8InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W8InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W8OnHandQuantity'
        /// </summary>
        [Test]
        public void W8OnHandQuantityTest()
        {
            // TODO unit test for the property 'W8OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W8OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W8OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W8OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W8OpenPOQuantity'
        /// </summary>
        [Test]
        public void W8OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W8OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W8OrderableQuantity'
        /// </summary>
        [Test]
        public void W8OrderableQuantityTest()
        {
            // TODO unit test for the property 'W8OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W8UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W8UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W8UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W8UnavailableQuantity'
        /// </summary>
        [Test]
        public void W8UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W8UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W8DaysOnHand'
        /// </summary>
        [Test]
        public void W8DaysOnHandTest()
        {
            // TODO unit test for the property 'W8DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W8StockStatus'
        /// </summary>
        [Test]
        public void W8StockStatusTest()
        {
            // TODO unit test for the property 'W8StockStatus'
        }
        /// <summary>
        /// Test the property 'W8EstimatedPallets'
        /// </summary>
        [Test]
        public void W8EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W8EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W8EstimatedCases'
        /// </summary>
        [Test]
        public void W8EstimatedCasesTest()
        {
            // TODO unit test for the property 'W8EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W8EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W8EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W8EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W8NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W8NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W8NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse9Id'
        /// </summary>
        [Test]
        public void Warehouse9IdTest()
        {
            // TODO unit test for the property 'Warehouse9Id'
        }
        /// <summary>
        /// Test the property 'W9AvailableQuantity'
        /// </summary>
        [Test]
        public void W9AvailableQuantityTest()
        {
            // TODO unit test for the property 'W9AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W9DamagedQuantity'
        /// </summary>
        [Test]
        public void W9DamagedQuantityTest()
        {
            // TODO unit test for the property 'W9DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W9InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W9InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W9InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W9OnHandQuantity'
        /// </summary>
        [Test]
        public void W9OnHandQuantityTest()
        {
            // TODO unit test for the property 'W9OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W9OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W9OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W9OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W9OpenPOQuantity'
        /// </summary>
        [Test]
        public void W9OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W9OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W9OrderableQuantity'
        /// </summary>
        [Test]
        public void W9OrderableQuantityTest()
        {
            // TODO unit test for the property 'W9OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W9UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W9UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W9UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W9UnavailableQuantity'
        /// </summary>
        [Test]
        public void W9UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W9UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W9DaysOnHand'
        /// </summary>
        [Test]
        public void W9DaysOnHandTest()
        {
            // TODO unit test for the property 'W9DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W9StockStatus'
        /// </summary>
        [Test]
        public void W9StockStatusTest()
        {
            // TODO unit test for the property 'W9StockStatus'
        }
        /// <summary>
        /// Test the property 'W9EstimatedPallets'
        /// </summary>
        [Test]
        public void W9EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W9EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W9EstimatedCases'
        /// </summary>
        [Test]
        public void W9EstimatedCasesTest()
        {
            // TODO unit test for the property 'W9EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W9EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W9EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W9EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W9NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W9NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W9NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'Warehouse10Id'
        /// </summary>
        [Test]
        public void Warehouse10IdTest()
        {
            // TODO unit test for the property 'Warehouse10Id'
        }
        /// <summary>
        /// Test the property 'W10AvailableQuantity'
        /// </summary>
        [Test]
        public void W10AvailableQuantityTest()
        {
            // TODO unit test for the property 'W10AvailableQuantity'
        }
        /// <summary>
        /// Test the property 'W10DamagedQuantity'
        /// </summary>
        [Test]
        public void W10DamagedQuantityTest()
        {
            // TODO unit test for the property 'W10DamagedQuantity'
        }
        /// <summary>
        /// Test the property 'W10InFulfillmentProcessQuantity'
        /// </summary>
        [Test]
        public void W10InFulfillmentProcessQuantityTest()
        {
            // TODO unit test for the property 'W10InFulfillmentProcessQuantity'
        }
        /// <summary>
        /// Test the property 'W10OnHandQuantity'
        /// </summary>
        [Test]
        public void W10OnHandQuantityTest()
        {
            // TODO unit test for the property 'W10OnHandQuantity'
        }
        /// <summary>
        /// Test the property 'W10OpenOrderQuantity'
        /// </summary>
        [Test]
        public void W10OpenOrderQuantityTest()
        {
            // TODO unit test for the property 'W10OpenOrderQuantity'
        }
        /// <summary>
        /// Test the property 'W10OpenPOQuantity'
        /// </summary>
        [Test]
        public void W10OpenPOQuantityTest()
        {
            // TODO unit test for the property 'W10OpenPOQuantity'
        }
        /// <summary>
        /// Test the property 'W10OrderableQuantity'
        /// </summary>
        [Test]
        public void W10OrderableQuantityTest()
        {
            // TODO unit test for the property 'W10OrderableQuantity'
        }
        /// <summary>
        /// Test the property 'W10UnallocatableQuantity'
        /// </summary>
        [Test]
        public void W10UnallocatableQuantityTest()
        {
            // TODO unit test for the property 'W10UnallocatableQuantity'
        }
        /// <summary>
        /// Test the property 'W10UnavailableQuantity'
        /// </summary>
        [Test]
        public void W10UnavailableQuantityTest()
        {
            // TODO unit test for the property 'W10UnavailableQuantity'
        }
        /// <summary>
        /// Test the property 'W10DaysOnHand'
        /// </summary>
        [Test]
        public void W10DaysOnHandTest()
        {
            // TODO unit test for the property 'W10DaysOnHand'
        }
        /// <summary>
        /// Test the property 'W10StockStatus'
        /// </summary>
        [Test]
        public void W10StockStatusTest()
        {
            // TODO unit test for the property 'W10StockStatus'
        }
        /// <summary>
        /// Test the property 'W10EstimatedPallets'
        /// </summary>
        [Test]
        public void W10EstimatedPalletsTest()
        {
            // TODO unit test for the property 'W10EstimatedPallets'
        }
        /// <summary>
        /// Test the property 'W10EstimatedCases'
        /// </summary>
        [Test]
        public void W10EstimatedCasesTest()
        {
            // TODO unit test for the property 'W10EstimatedCases'
        }
        /// <summary>
        /// Test the property 'W10EstimatedInnerPacks'
        /// </summary>
        [Test]
        public void W10EstimatedInnerPacksTest()
        {
            // TODO unit test for the property 'W10EstimatedInnerPacks'
        }
        /// <summary>
        /// Test the property 'W10NextRequestedDeliveryDate'
        /// </summary>
        [Test]
        public void W10NextRequestedDeliveryDateTest()
        {
            // TODO unit test for the property 'W10NextRequestedDeliveryDate'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }

    }

}
