/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Infoplus.Api;
using Infoplus.Model;
using Infoplus.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Infoplus.Test
{
    /// <summary>
    ///  Class for testing ParcelInvoiceLine
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ParcelInvoiceLineTests
    {
        // TODO uncomment below to declare an instance variable for ParcelInvoiceLine
        //private ParcelInvoiceLine instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParcelInvoiceLine
            //instance = new ParcelInvoiceLine();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParcelInvoiceLine
        /// </summary>
        [Test]
        public void ParcelInvoiceLineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ParcelInvoiceLine
            //Assert.IsInstanceOfType<ParcelInvoiceLine> (instance, "variable 'instance' is a ParcelInvoiceLine");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'InvoiceNoId'
        /// </summary>
        [Test]
        public void InvoiceNoIdTest()
        {
            // TODO unit test for the property 'InvoiceNoId'
        }
        /// <summary>
        /// Test the property 'CreateDate'
        /// </summary>
        [Test]
        public void CreateDateTest()
        {
            // TODO unit test for the property 'CreateDate'
        }
        /// <summary>
        /// Test the property 'ModifyDate'
        /// </summary>
        [Test]
        public void ModifyDateTest()
        {
            // TODO unit test for the property 'ModifyDate'
        }
        /// <summary>
        /// Test the property 'LobId'
        /// </summary>
        [Test]
        public void LobIdTest()
        {
            // TODO unit test for the property 'LobId'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Test]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }
        /// <summary>
        /// Test the property 'TrackingNo'
        /// </summary>
        [Test]
        public void TrackingNoTest()
        {
            // TODO unit test for the property 'TrackingNo'
        }
        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Test]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }
        /// <summary>
        /// Test the property 'Zone'
        /// </summary>
        [Test]
        public void ZoneTest()
        {
            // TODO unit test for the property 'Zone'
        }
        /// <summary>
        /// Test the property 'Dim1'
        /// </summary>
        [Test]
        public void Dim1Test()
        {
            // TODO unit test for the property 'Dim1'
        }
        /// <summary>
        /// Test the property 'Dim2'
        /// </summary>
        [Test]
        public void Dim2Test()
        {
            // TODO unit test for the property 'Dim2'
        }
        /// <summary>
        /// Test the property 'Dim3'
        /// </summary>
        [Test]
        public void Dim3Test()
        {
            // TODO unit test for the property 'Dim3'
        }
        /// <summary>
        /// Test the property 'EnteredWeight'
        /// </summary>
        [Test]
        public void EnteredWeightTest()
        {
            // TODO unit test for the property 'EnteredWeight'
        }
        /// <summary>
        /// Test the property 'ActualWeight'
        /// </summary>
        [Test]
        public void ActualWeightTest()
        {
            // TODO unit test for the property 'ActualWeight'
        }
        /// <summary>
        /// Test the property 'BilledWeight'
        /// </summary>
        [Test]
        public void BilledWeightTest()
        {
            // TODO unit test for the property 'BilledWeight'
        }
        /// <summary>
        /// Test the property 'EnteredWeightUnit'
        /// </summary>
        [Test]
        public void EnteredWeightUnitTest()
        {
            // TODO unit test for the property 'EnteredWeightUnit'
        }
        /// <summary>
        /// Test the property 'ActualWeightUnit'
        /// </summary>
        [Test]
        public void ActualWeightUnitTest()
        {
            // TODO unit test for the property 'ActualWeightUnit'
        }
        /// <summary>
        /// Test the property 'BilledWeightUnit'
        /// </summary>
        [Test]
        public void BilledWeightUnitTest()
        {
            // TODO unit test for the property 'BilledWeightUnit'
        }
        /// <summary>
        /// Test the property 'CustomerReference'
        /// </summary>
        [Test]
        public void CustomerReferenceTest()
        {
            // TODO unit test for the property 'CustomerReference'
        }
        /// <summary>
        /// Test the property 'ShipmentReference'
        /// </summary>
        [Test]
        public void ShipmentReferenceTest()
        {
            // TODO unit test for the property 'ShipmentReference'
        }
        /// <summary>
        /// Test the property 'Reference3'
        /// </summary>
        [Test]
        public void Reference3Test()
        {
            // TODO unit test for the property 'Reference3'
        }
        /// <summary>
        /// Test the property 'Reference4'
        /// </summary>
        [Test]
        public void Reference4Test()
        {
            // TODO unit test for the property 'Reference4'
        }
        /// <summary>
        /// Test the property 'Reference5'
        /// </summary>
        [Test]
        public void Reference5Test()
        {
            // TODO unit test for the property 'Reference5'
        }
        /// <summary>
        /// Test the property 'Reference6'
        /// </summary>
        [Test]
        public void Reference6Test()
        {
            // TODO unit test for the property 'Reference6'
        }
        /// <summary>
        /// Test the property 'Reference7'
        /// </summary>
        [Test]
        public void Reference7Test()
        {
            // TODO unit test for the property 'Reference7'
        }
        /// <summary>
        /// Test the property 'ShipFromName'
        /// </summary>
        [Test]
        public void ShipFromNameTest()
        {
            // TODO unit test for the property 'ShipFromName'
        }
        /// <summary>
        /// Test the property 'ShipFromCompany'
        /// </summary>
        [Test]
        public void ShipFromCompanyTest()
        {
            // TODO unit test for the property 'ShipFromCompany'
        }
        /// <summary>
        /// Test the property 'ShipFromStreet1'
        /// </summary>
        [Test]
        public void ShipFromStreet1Test()
        {
            // TODO unit test for the property 'ShipFromStreet1'
        }
        /// <summary>
        /// Test the property 'ShipFromStreet2'
        /// </summary>
        [Test]
        public void ShipFromStreet2Test()
        {
            // TODO unit test for the property 'ShipFromStreet2'
        }
        /// <summary>
        /// Test the property 'ShipFromCity'
        /// </summary>
        [Test]
        public void ShipFromCityTest()
        {
            // TODO unit test for the property 'ShipFromCity'
        }
        /// <summary>
        /// Test the property 'ShipFromState'
        /// </summary>
        [Test]
        public void ShipFromStateTest()
        {
            // TODO unit test for the property 'ShipFromState'
        }
        /// <summary>
        /// Test the property 'ShipFromZip'
        /// </summary>
        [Test]
        public void ShipFromZipTest()
        {
            // TODO unit test for the property 'ShipFromZip'
        }
        /// <summary>
        /// Test the property 'ShipFromCountry'
        /// </summary>
        [Test]
        public void ShipFromCountryTest()
        {
            // TODO unit test for the property 'ShipFromCountry'
        }
        /// <summary>
        /// Test the property 'ShipToName'
        /// </summary>
        [Test]
        public void ShipToNameTest()
        {
            // TODO unit test for the property 'ShipToName'
        }
        /// <summary>
        /// Test the property 'ShipToCompany'
        /// </summary>
        [Test]
        public void ShipToCompanyTest()
        {
            // TODO unit test for the property 'ShipToCompany'
        }
        /// <summary>
        /// Test the property 'ShipToStreet1'
        /// </summary>
        [Test]
        public void ShipToStreet1Test()
        {
            // TODO unit test for the property 'ShipToStreet1'
        }
        /// <summary>
        /// Test the property 'ShipToStreet2'
        /// </summary>
        [Test]
        public void ShipToStreet2Test()
        {
            // TODO unit test for the property 'ShipToStreet2'
        }
        /// <summary>
        /// Test the property 'ShipToCity'
        /// </summary>
        [Test]
        public void ShipToCityTest()
        {
            // TODO unit test for the property 'ShipToCity'
        }
        /// <summary>
        /// Test the property 'ShipToState'
        /// </summary>
        [Test]
        public void ShipToStateTest()
        {
            // TODO unit test for the property 'ShipToState'
        }
        /// <summary>
        /// Test the property 'ShipToZip'
        /// </summary>
        [Test]
        public void ShipToZipTest()
        {
            // TODO unit test for the property 'ShipToZip'
        }
        /// <summary>
        /// Test the property 'ShipToCountry'
        /// </summary>
        [Test]
        public void ShipToCountryTest()
        {
            // TODO unit test for the property 'ShipToCountry'
        }
        /// <summary>
        /// Test the property 'OriginalShipToName'
        /// </summary>
        [Test]
        public void OriginalShipToNameTest()
        {
            // TODO unit test for the property 'OriginalShipToName'
        }
        /// <summary>
        /// Test the property 'OriginalShipToCompany'
        /// </summary>
        [Test]
        public void OriginalShipToCompanyTest()
        {
            // TODO unit test for the property 'OriginalShipToCompany'
        }
        /// <summary>
        /// Test the property 'OriginalShipToStreet1'
        /// </summary>
        [Test]
        public void OriginalShipToStreet1Test()
        {
            // TODO unit test for the property 'OriginalShipToStreet1'
        }
        /// <summary>
        /// Test the property 'OriginalShipToStreet2'
        /// </summary>
        [Test]
        public void OriginalShipToStreet2Test()
        {
            // TODO unit test for the property 'OriginalShipToStreet2'
        }
        /// <summary>
        /// Test the property 'OriginalShipToCity'
        /// </summary>
        [Test]
        public void OriginalShipToCityTest()
        {
            // TODO unit test for the property 'OriginalShipToCity'
        }
        /// <summary>
        /// Test the property 'OriginalShipToState'
        /// </summary>
        [Test]
        public void OriginalShipToStateTest()
        {
            // TODO unit test for the property 'OriginalShipToState'
        }
        /// <summary>
        /// Test the property 'OriginalShipToZip'
        /// </summary>
        [Test]
        public void OriginalShipToZipTest()
        {
            // TODO unit test for the property 'OriginalShipToZip'
        }
        /// <summary>
        /// Test the property 'OriginalShipToCountry'
        /// </summary>
        [Test]
        public void OriginalShipToCountryTest()
        {
            // TODO unit test for the property 'OriginalShipToCountry'
        }
        /// <summary>
        /// Test the property 'ThirdPartyName'
        /// </summary>
        [Test]
        public void ThirdPartyNameTest()
        {
            // TODO unit test for the property 'ThirdPartyName'
        }
        /// <summary>
        /// Test the property 'ThirdPartyCompany'
        /// </summary>
        [Test]
        public void ThirdPartyCompanyTest()
        {
            // TODO unit test for the property 'ThirdPartyCompany'
        }
        /// <summary>
        /// Test the property 'ThirdPartyStreet1'
        /// </summary>
        [Test]
        public void ThirdPartyStreet1Test()
        {
            // TODO unit test for the property 'ThirdPartyStreet1'
        }
        /// <summary>
        /// Test the property 'ThirdPartyStreet2'
        /// </summary>
        [Test]
        public void ThirdPartyStreet2Test()
        {
            // TODO unit test for the property 'ThirdPartyStreet2'
        }
        /// <summary>
        /// Test the property 'ThirdPartyCity'
        /// </summary>
        [Test]
        public void ThirdPartyCityTest()
        {
            // TODO unit test for the property 'ThirdPartyCity'
        }
        /// <summary>
        /// Test the property 'ThirdPartyState'
        /// </summary>
        [Test]
        public void ThirdPartyStateTest()
        {
            // TODO unit test for the property 'ThirdPartyState'
        }
        /// <summary>
        /// Test the property 'ThirdPartyZip'
        /// </summary>
        [Test]
        public void ThirdPartyZipTest()
        {
            // TODO unit test for the property 'ThirdPartyZip'
        }
        /// <summary>
        /// Test the property 'ThirdPartyCountry'
        /// </summary>
        [Test]
        public void ThirdPartyCountryTest()
        {
            // TODO unit test for the property 'ThirdPartyCountry'
        }
        /// <summary>
        /// Test the property 'SoldToName'
        /// </summary>
        [Test]
        public void SoldToNameTest()
        {
            // TODO unit test for the property 'SoldToName'
        }
        /// <summary>
        /// Test the property 'SoldToCompany'
        /// </summary>
        [Test]
        public void SoldToCompanyTest()
        {
            // TODO unit test for the property 'SoldToCompany'
        }
        /// <summary>
        /// Test the property 'SoldToStreet1'
        /// </summary>
        [Test]
        public void SoldToStreet1Test()
        {
            // TODO unit test for the property 'SoldToStreet1'
        }
        /// <summary>
        /// Test the property 'SoldToStreet2'
        /// </summary>
        [Test]
        public void SoldToStreet2Test()
        {
            // TODO unit test for the property 'SoldToStreet2'
        }
        /// <summary>
        /// Test the property 'SoldToCity'
        /// </summary>
        [Test]
        public void SoldToCityTest()
        {
            // TODO unit test for the property 'SoldToCity'
        }
        /// <summary>
        /// Test the property 'SoldToState'
        /// </summary>
        [Test]
        public void SoldToStateTest()
        {
            // TODO unit test for the property 'SoldToState'
        }
        /// <summary>
        /// Test the property 'SoldToZip'
        /// </summary>
        [Test]
        public void SoldToZipTest()
        {
            // TODO unit test for the property 'SoldToZip'
        }
        /// <summary>
        /// Test the property 'SoldToCountry'
        /// </summary>
        [Test]
        public void SoldToCountryTest()
        {
            // TODO unit test for the property 'SoldToCountry'
        }
        /// <summary>
        /// Test the property 'FreightServiceType'
        /// </summary>
        [Test]
        public void FreightServiceTypeTest()
        {
            // TODO unit test for the property 'FreightServiceType'
        }
        /// <summary>
        /// Test the property 'NetCharges'
        /// </summary>
        [Test]
        public void NetChargesTest()
        {
            // TODO unit test for the property 'NetCharges'
        }
        /// <summary>
        /// Test the property 'BaseFreight'
        /// </summary>
        [Test]
        public void BaseFreightTest()
        {
            // TODO unit test for the property 'BaseFreight'
        }
        /// <summary>
        /// Test the property 'GrossCharges'
        /// </summary>
        [Test]
        public void GrossChargesTest()
        {
            // TODO unit test for the property 'GrossCharges'
        }
        /// <summary>
        /// Test the property 'FuelCharge'
        /// </summary>
        [Test]
        public void FuelChargeTest()
        {
            // TODO unit test for the property 'FuelCharge'
        }
        /// <summary>
        /// Test the property 'ResidentialCharge'
        /// </summary>
        [Test]
        public void ResidentialChargeTest()
        {
            // TODO unit test for the property 'ResidentialCharge'
        }
        /// <summary>
        /// Test the property 'AdultSignatureCharge'
        /// </summary>
        [Test]
        public void AdultSignatureChargeTest()
        {
            // TODO unit test for the property 'AdultSignatureCharge'
        }
        /// <summary>
        /// Test the property 'DeliveryAreaCharge'
        /// </summary>
        [Test]
        public void DeliveryAreaChargeTest()
        {
            // TODO unit test for the property 'DeliveryAreaCharge'
        }
        /// <summary>
        /// Test the property 'DeliveryAreaChargeExtended'
        /// </summary>
        [Test]
        public void DeliveryAreaChargeExtendedTest()
        {
            // TODO unit test for the property 'DeliveryAreaChargeExtended'
        }
        /// <summary>
        /// Test the property 'AddressCorrectionCharge'
        /// </summary>
        [Test]
        public void AddressCorrectionChargeTest()
        {
            // TODO unit test for the property 'AddressCorrectionCharge'
        }
        /// <summary>
        /// Test the property 'ExtraCharge1Name'
        /// </summary>
        [Test]
        public void ExtraCharge1NameTest()
        {
            // TODO unit test for the property 'ExtraCharge1Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge1Amount'
        /// </summary>
        [Test]
        public void ExtraCharge1AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge1Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge2Name'
        /// </summary>
        [Test]
        public void ExtraCharge2NameTest()
        {
            // TODO unit test for the property 'ExtraCharge2Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge2Amount'
        /// </summary>
        [Test]
        public void ExtraCharge2AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge2Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge3Name'
        /// </summary>
        [Test]
        public void ExtraCharge3NameTest()
        {
            // TODO unit test for the property 'ExtraCharge3Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge3Amount'
        /// </summary>
        [Test]
        public void ExtraCharge3AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge3Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge4Name'
        /// </summary>
        [Test]
        public void ExtraCharge4NameTest()
        {
            // TODO unit test for the property 'ExtraCharge4Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge4Amount'
        /// </summary>
        [Test]
        public void ExtraCharge4AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge4Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge5Name'
        /// </summary>
        [Test]
        public void ExtraCharge5NameTest()
        {
            // TODO unit test for the property 'ExtraCharge5Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge5Amount'
        /// </summary>
        [Test]
        public void ExtraCharge5AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge5Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge6Name'
        /// </summary>
        [Test]
        public void ExtraCharge6NameTest()
        {
            // TODO unit test for the property 'ExtraCharge6Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge6Amount'
        /// </summary>
        [Test]
        public void ExtraCharge6AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge6Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge7Name'
        /// </summary>
        [Test]
        public void ExtraCharge7NameTest()
        {
            // TODO unit test for the property 'ExtraCharge7Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge7Amount'
        /// </summary>
        [Test]
        public void ExtraCharge7AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge7Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge8Name'
        /// </summary>
        [Test]
        public void ExtraCharge8NameTest()
        {
            // TODO unit test for the property 'ExtraCharge8Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge8Amount'
        /// </summary>
        [Test]
        public void ExtraCharge8AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge8Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge9Name'
        /// </summary>
        [Test]
        public void ExtraCharge9NameTest()
        {
            // TODO unit test for the property 'ExtraCharge9Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge9Amount'
        /// </summary>
        [Test]
        public void ExtraCharge9AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge9Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge10Name'
        /// </summary>
        [Test]
        public void ExtraCharge10NameTest()
        {
            // TODO unit test for the property 'ExtraCharge10Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge10Amount'
        /// </summary>
        [Test]
        public void ExtraCharge10AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge10Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge11Name'
        /// </summary>
        [Test]
        public void ExtraCharge11NameTest()
        {
            // TODO unit test for the property 'ExtraCharge11Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge11Amount'
        /// </summary>
        [Test]
        public void ExtraCharge11AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge11Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge12Name'
        /// </summary>
        [Test]
        public void ExtraCharge12NameTest()
        {
            // TODO unit test for the property 'ExtraCharge12Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge12Amount'
        /// </summary>
        [Test]
        public void ExtraCharge12AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge12Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge13Name'
        /// </summary>
        [Test]
        public void ExtraCharge13NameTest()
        {
            // TODO unit test for the property 'ExtraCharge13Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge13Amount'
        /// </summary>
        [Test]
        public void ExtraCharge13AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge13Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge14Name'
        /// </summary>
        [Test]
        public void ExtraCharge14NameTest()
        {
            // TODO unit test for the property 'ExtraCharge14Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge14Amount'
        /// </summary>
        [Test]
        public void ExtraCharge14AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge14Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge15Name'
        /// </summary>
        [Test]
        public void ExtraCharge15NameTest()
        {
            // TODO unit test for the property 'ExtraCharge15Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge15Amount'
        /// </summary>
        [Test]
        public void ExtraCharge15AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge15Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge16Name'
        /// </summary>
        [Test]
        public void ExtraCharge16NameTest()
        {
            // TODO unit test for the property 'ExtraCharge16Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge16Amount'
        /// </summary>
        [Test]
        public void ExtraCharge16AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge16Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge17Name'
        /// </summary>
        [Test]
        public void ExtraCharge17NameTest()
        {
            // TODO unit test for the property 'ExtraCharge17Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge17Amount'
        /// </summary>
        [Test]
        public void ExtraCharge17AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge17Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge18Name'
        /// </summary>
        [Test]
        public void ExtraCharge18NameTest()
        {
            // TODO unit test for the property 'ExtraCharge18Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge18Amount'
        /// </summary>
        [Test]
        public void ExtraCharge18AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge18Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge19Name'
        /// </summary>
        [Test]
        public void ExtraCharge19NameTest()
        {
            // TODO unit test for the property 'ExtraCharge19Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge19Amount'
        /// </summary>
        [Test]
        public void ExtraCharge19AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge19Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge20Name'
        /// </summary>
        [Test]
        public void ExtraCharge20NameTest()
        {
            // TODO unit test for the property 'ExtraCharge20Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge20Amount'
        /// </summary>
        [Test]
        public void ExtraCharge20AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge20Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge21Name'
        /// </summary>
        [Test]
        public void ExtraCharge21NameTest()
        {
            // TODO unit test for the property 'ExtraCharge21Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge21Amount'
        /// </summary>
        [Test]
        public void ExtraCharge21AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge21Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge22Name'
        /// </summary>
        [Test]
        public void ExtraCharge22NameTest()
        {
            // TODO unit test for the property 'ExtraCharge22Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge22Amount'
        /// </summary>
        [Test]
        public void ExtraCharge22AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge22Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge23Name'
        /// </summary>
        [Test]
        public void ExtraCharge23NameTest()
        {
            // TODO unit test for the property 'ExtraCharge23Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge23Amount'
        /// </summary>
        [Test]
        public void ExtraCharge23AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge23Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge24Name'
        /// </summary>
        [Test]
        public void ExtraCharge24NameTest()
        {
            // TODO unit test for the property 'ExtraCharge24Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge24Amount'
        /// </summary>
        [Test]
        public void ExtraCharge24AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge24Amount'
        }
        /// <summary>
        /// Test the property 'ExtraCharge25Name'
        /// </summary>
        [Test]
        public void ExtraCharge25NameTest()
        {
            // TODO unit test for the property 'ExtraCharge25Name'
        }
        /// <summary>
        /// Test the property 'ExtraCharge25Amount'
        /// </summary>
        [Test]
        public void ExtraCharge25AmountTest()
        {
            // TODO unit test for the property 'ExtraCharge25Amount'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }

    }

}
