/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: v1.0
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Infoplus.Api;
using Infoplus.Model;
using Infoplus.Client;
using System.Reflection;

namespace Infoplus.Test
{
    /// <summary>
    ///  Class for testing ReceivingWorksheetLineItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReceivingWorksheetLineItemTests
    {
        // TODO uncomment below to declare an instance variable for ReceivingWorksheetLineItem
        //private ReceivingWorksheetLineItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReceivingWorksheetLineItem
            //instance = new ReceivingWorksheetLineItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReceivingWorksheetLineItem
        /// </summary>
        [Test]
        public void ReceivingWorksheetLineItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReceivingWorksheetLineItem
            //Assert.IsInstanceOfType<ReceivingWorksheetLineItem> (instance, "variable 'instance' is a ReceivingWorksheetLineItem");
        }

        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Test]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'FullDescription'
        /// </summary>
        [Test]
        public void FullDescriptionTest()
        {
            // TODO unit test for the property 'FullDescription'
        }
        /// <summary>
        /// Test the property 'OrderedQty'
        /// </summary>
        [Test]
        public void OrderedQtyTest()
        {
            // TODO unit test for the property 'OrderedQty'
        }
        /// <summary>
        /// Test the property 'PrevReceivedQty'
        /// </summary>
        [Test]
        public void PrevReceivedQtyTest()
        {
            // TODO unit test for the property 'PrevReceivedQty'
        }
        /// <summary>
        /// Test the property 'UnreceivedQty'
        /// </summary>
        [Test]
        public void UnreceivedQtyTest()
        {
            // TODO unit test for the property 'UnreceivedQty'
        }
        /// <summary>
        /// Test the property 'ReceivingQty'
        /// </summary>
        [Test]
        public void ReceivingQtyTest()
        {
            // TODO unit test for the property 'ReceivingQty'
        }
        /// <summary>
        /// Test the property 'UnitCode'
        /// </summary>
        [Test]
        public void UnitCodeTest()
        {
            // TODO unit test for the property 'UnitCode'
        }
        /// <summary>
        /// Test the property 'WrapCode'
        /// </summary>
        [Test]
        public void WrapCodeTest()
        {
            // TODO unit test for the property 'WrapCode'
        }
        /// <summary>
        /// Test the property 'UnitsPerWrap'
        /// </summary>
        [Test]
        public void UnitsPerWrapTest()
        {
            // TODO unit test for the property 'UnitsPerWrap'
        }
        /// <summary>
        /// Test the property 'UnitsPerCase'
        /// </summary>
        [Test]
        public void UnitsPerCaseTest()
        {
            // TODO unit test for the property 'UnitsPerCase'
        }
        /// <summary>
        /// Test the property 'CasesPerPallet'
        /// </summary>
        [Test]
        public void CasesPerPalletTest()
        {
            // TODO unit test for the property 'CasesPerPallet'
        }
        /// <summary>
        /// Test the property 'WeightPerWrap'
        /// </summary>
        [Test]
        public void WeightPerWrapTest()
        {
            // TODO unit test for the property 'WeightPerWrap'
        }
        /// <summary>
        /// Test the property 'WeightPerCase'
        /// </summary>
        [Test]
        public void WeightPerCaseTest()
        {
            // TODO unit test for the property 'WeightPerCase'
        }
        /// <summary>
        /// Test the property 'ProductionLot'
        /// </summary>
        [Test]
        public void ProductionLotTest()
        {
            // TODO unit test for the property 'ProductionLot'
        }
        /// <summary>
        /// Test the property 'RevisionDate'
        /// </summary>
        [Test]
        public void RevisionDateTest()
        {
            // TODO unit test for the property 'RevisionDate'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Test]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'CartonLength'
        /// </summary>
        [Test]
        public void CartonLengthTest()
        {
            // TODO unit test for the property 'CartonLength'
        }
        /// <summary>
        /// Test the property 'CartonWidth'
        /// </summary>
        [Test]
        public void CartonWidthTest()
        {
            // TODO unit test for the property 'CartonWidth'
        }
        /// <summary>
        /// Test the property 'CartonHeight'
        /// </summary>
        [Test]
        public void CartonHeightTest()
        {
            // TODO unit test for the property 'CartonHeight'
        }
        /// <summary>
        /// Test the property 'PutAwayPlans'
        /// </summary>
        [Test]
        public void PutAwayPlansTest()
        {
            // TODO unit test for the property 'PutAwayPlans'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
