/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: v3.0
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Infoplus.Client.SwaggerDateConverter;

namespace Infoplus.Model
{
    /// <summary>
    /// Warehouse
    /// </summary>
    [DataContract]
    public partial class Warehouse :  IEquatable<Warehouse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Warehouse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Warehouse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Warehouse" /> class.
        /// </summary>
        /// <param name="Name">Name (required).</param>
        /// <param name="Address">Address.</param>
        /// <param name="Company">Company (required).</param>
        /// <param name="Street1">Street1 (required).</param>
        /// <param name="Street2">Street2.</param>
        /// <param name="Street3">Street3.</param>
        /// <param name="City">City (required).</param>
        /// <param name="State">State.</param>
        /// <param name="Zip">Zip (required).</param>
        /// <param name="Country">Country (required).</param>
        /// <param name="Phone">Phone (required).</param>
        /// <param name="LocationBarcodePrefix">LocationBarcodePrefix.</param>
        /// <param name="LpnPrefix">LpnPrefix.</param>
        /// <param name="TimeZone">TimeZone.</param>
        /// <param name="PackStationAllowPackingBeforePickWorkIsComplete">PackStationAllowPackingBeforePickWorkIsComplete (required) (default to false).</param>
        /// <param name="PackStationSkipCartonLPN">PackStationSkipCartonLPN (required) (default to false).</param>
        /// <param name="PackStationRequireConfirmOnError">PackStationRequireConfirmOnError (required) (default to false).</param>
        /// <param name="PackStationAllowScanningSKUToIdentifyOrders">PackStationAllowScanningSKUToIdentifyOrders (required) (default to false).</param>
        /// <param name="PackStationAllowEntryOfItemQuantities">PackStationAllowEntryOfItemQuantities (required) (default to false).</param>
        /// <param name="ShipStationWeightCheckPackedOrders">ShipStationWeightCheckPackedOrders (required) (default to false).</param>
        /// <param name="ShipStationShowUserWeightCheckExceptions">ShipStationShowUserWeightCheckExceptions (required) (default to false).</param>
        /// <param name="ShipStationAutoPrintPreGeneratedLabels">ShipStationAutoPrintPreGeneratedLabels (required) (default to false).</param>
        /// <param name="ShipStationAllowScanningSKUToIdentifyOrders">ShipStationAllowScanningSKUToIdentifyOrders (required) (default to false).</param>
        /// <param name="CustomFields">CustomFields.</param>
        public Warehouse(string Name = default(string), string Address = default(string), string Company = default(string), string Street1 = default(string), string Street2 = default(string), string Street3 = default(string), string City = default(string), string State = default(string), string Zip = default(string), string Country = default(string), string Phone = default(string), string LocationBarcodePrefix = default(string), string LpnPrefix = default(string), string TimeZone = default(string), bool? PackStationAllowPackingBeforePickWorkIsComplete = false, bool? PackStationSkipCartonLPN = false, bool? PackStationRequireConfirmOnError = false, bool? PackStationAllowScanningSKUToIdentifyOrders = false, bool? PackStationAllowEntryOfItemQuantities = false, bool? ShipStationWeightCheckPackedOrders = false, bool? ShipStationShowUserWeightCheckExceptions = false, bool? ShipStationAutoPrintPreGeneratedLabels = false, bool? ShipStationAllowScanningSKUToIdentifyOrders = false, Dictionary<string, Object> CustomFields = default(Dictionary<string, Object>))
        {
            // to ensure "Name" is required (not null)
            if (Name == null)
            {
                throw new InvalidDataException("Name is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.Name = Name;
            }
            // to ensure "Company" is required (not null)
            if (Company == null)
            {
                throw new InvalidDataException("Company is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.Company = Company;
            }
            // to ensure "Street1" is required (not null)
            if (Street1 == null)
            {
                throw new InvalidDataException("Street1 is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.Street1 = Street1;
            }
            // to ensure "City" is required (not null)
            if (City == null)
            {
                throw new InvalidDataException("City is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.City = City;
            }
            // to ensure "Zip" is required (not null)
            if (Zip == null)
            {
                throw new InvalidDataException("Zip is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.Zip = Zip;
            }
            // to ensure "Country" is required (not null)
            if (Country == null)
            {
                throw new InvalidDataException("Country is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.Country = Country;
            }
            // to ensure "Phone" is required (not null)
            if (Phone == null)
            {
                throw new InvalidDataException("Phone is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.Phone = Phone;
            }
            // to ensure "PackStationAllowPackingBeforePickWorkIsComplete" is required (not null)
            if (PackStationAllowPackingBeforePickWorkIsComplete == null)
            {
                throw new InvalidDataException("PackStationAllowPackingBeforePickWorkIsComplete is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.PackStationAllowPackingBeforePickWorkIsComplete = PackStationAllowPackingBeforePickWorkIsComplete;
            }
            // to ensure "PackStationSkipCartonLPN" is required (not null)
            if (PackStationSkipCartonLPN == null)
            {
                throw new InvalidDataException("PackStationSkipCartonLPN is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.PackStationSkipCartonLPN = PackStationSkipCartonLPN;
            }
            // to ensure "PackStationRequireConfirmOnError" is required (not null)
            if (PackStationRequireConfirmOnError == null)
            {
                throw new InvalidDataException("PackStationRequireConfirmOnError is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.PackStationRequireConfirmOnError = PackStationRequireConfirmOnError;
            }
            // to ensure "PackStationAllowScanningSKUToIdentifyOrders" is required (not null)
            if (PackStationAllowScanningSKUToIdentifyOrders == null)
            {
                throw new InvalidDataException("PackStationAllowScanningSKUToIdentifyOrders is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.PackStationAllowScanningSKUToIdentifyOrders = PackStationAllowScanningSKUToIdentifyOrders;
            }
            // to ensure "PackStationAllowEntryOfItemQuantities" is required (not null)
            if (PackStationAllowEntryOfItemQuantities == null)
            {
                throw new InvalidDataException("PackStationAllowEntryOfItemQuantities is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.PackStationAllowEntryOfItemQuantities = PackStationAllowEntryOfItemQuantities;
            }
            // to ensure "ShipStationWeightCheckPackedOrders" is required (not null)
            if (ShipStationWeightCheckPackedOrders == null)
            {
                throw new InvalidDataException("ShipStationWeightCheckPackedOrders is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.ShipStationWeightCheckPackedOrders = ShipStationWeightCheckPackedOrders;
            }
            // to ensure "ShipStationShowUserWeightCheckExceptions" is required (not null)
            if (ShipStationShowUserWeightCheckExceptions == null)
            {
                throw new InvalidDataException("ShipStationShowUserWeightCheckExceptions is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.ShipStationShowUserWeightCheckExceptions = ShipStationShowUserWeightCheckExceptions;
            }
            // to ensure "ShipStationAutoPrintPreGeneratedLabels" is required (not null)
            if (ShipStationAutoPrintPreGeneratedLabels == null)
            {
                throw new InvalidDataException("ShipStationAutoPrintPreGeneratedLabels is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.ShipStationAutoPrintPreGeneratedLabels = ShipStationAutoPrintPreGeneratedLabels;
            }
            // to ensure "ShipStationAllowScanningSKUToIdentifyOrders" is required (not null)
            if (ShipStationAllowScanningSKUToIdentifyOrders == null)
            {
                throw new InvalidDataException("ShipStationAllowScanningSKUToIdentifyOrders is a required property for Warehouse and cannot be null");
            }
            else
            {
                this.ShipStationAllowScanningSKUToIdentifyOrders = ShipStationAllowScanningSKUToIdentifyOrders;
            }
            this.Address = Address;
            this.Street2 = Street2;
            this.Street3 = Street3;
            this.State = State;
            this.LocationBarcodePrefix = LocationBarcodePrefix;
            this.LpnPrefix = LpnPrefix;
            this.TimeZone = TimeZone;
            this.CustomFields = CustomFields;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; private set; }

        /// <summary>
        /// Gets or Sets _Client
        /// </summary>
        [DataMember(Name="client", EmitDefaultValue=false)]
        public int? _Client { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Company
        /// </summary>
        [DataMember(Name="company", EmitDefaultValue=false)]
        public string Company { get; set; }

        /// <summary>
        /// Gets or Sets Street1
        /// </summary>
        [DataMember(Name="street1", EmitDefaultValue=false)]
        public string Street1 { get; set; }

        /// <summary>
        /// Gets or Sets Street2
        /// </summary>
        [DataMember(Name="street2", EmitDefaultValue=false)]
        public string Street2 { get; set; }

        /// <summary>
        /// Gets or Sets Street3
        /// </summary>
        [DataMember(Name="street3", EmitDefaultValue=false)]
        public string Street3 { get; set; }

        /// <summary>
        /// Gets or Sets City
        /// </summary>
        [DataMember(Name="city", EmitDefaultValue=false)]
        public string City { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets Zip
        /// </summary>
        [DataMember(Name="zip", EmitDefaultValue=false)]
        public string Zip { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [DataMember(Name="phone", EmitDefaultValue=false)]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or Sets LocationBarcodePrefix
        /// </summary>
        [DataMember(Name="locationBarcodePrefix", EmitDefaultValue=false)]
        public string LocationBarcodePrefix { get; set; }

        /// <summary>
        /// Gets or Sets LpnPrefix
        /// </summary>
        [DataMember(Name="lpnPrefix", EmitDefaultValue=false)]
        public string LpnPrefix { get; set; }

        /// <summary>
        /// Gets or Sets TimeZone
        /// </summary>
        [DataMember(Name="timeZone", EmitDefaultValue=false)]
        public string TimeZone { get; set; }

        /// <summary>
        /// Gets or Sets PackStationAllowPackingBeforePickWorkIsComplete
        /// </summary>
        [DataMember(Name="packStationAllowPackingBeforePickWorkIsComplete", EmitDefaultValue=false)]
        public bool? PackStationAllowPackingBeforePickWorkIsComplete { get; set; }

        /// <summary>
        /// Gets or Sets PackStationSkipCartonLPN
        /// </summary>
        [DataMember(Name="packStationSkipCartonLPN", EmitDefaultValue=false)]
        public bool? PackStationSkipCartonLPN { get; set; }

        /// <summary>
        /// Gets or Sets PackStationRequireConfirmOnError
        /// </summary>
        [DataMember(Name="packStationRequireConfirmOnError", EmitDefaultValue=false)]
        public bool? PackStationRequireConfirmOnError { get; set; }

        /// <summary>
        /// Gets or Sets PackStationAllowScanningSKUToIdentifyOrders
        /// </summary>
        [DataMember(Name="packStationAllowScanningSKUToIdentifyOrders", EmitDefaultValue=false)]
        public bool? PackStationAllowScanningSKUToIdentifyOrders { get; set; }

        /// <summary>
        /// Gets or Sets PackStationAllowEntryOfItemQuantities
        /// </summary>
        [DataMember(Name="packStationAllowEntryOfItemQuantities", EmitDefaultValue=false)]
        public bool? PackStationAllowEntryOfItemQuantities { get; set; }

        /// <summary>
        /// Gets or Sets ShipStationWeightCheckPackedOrders
        /// </summary>
        [DataMember(Name="shipStationWeightCheckPackedOrders", EmitDefaultValue=false)]
        public bool? ShipStationWeightCheckPackedOrders { get; set; }

        /// <summary>
        /// Gets or Sets ShipStationShowUserWeightCheckExceptions
        /// </summary>
        [DataMember(Name="shipStationShowUserWeightCheckExceptions", EmitDefaultValue=false)]
        public bool? ShipStationShowUserWeightCheckExceptions { get; set; }

        /// <summary>
        /// Gets or Sets ShipStationAutoPrintPreGeneratedLabels
        /// </summary>
        [DataMember(Name="shipStationAutoPrintPreGeneratedLabels", EmitDefaultValue=false)]
        public bool? ShipStationAutoPrintPreGeneratedLabels { get; set; }

        /// <summary>
        /// Gets or Sets ShipStationAllowScanningSKUToIdentifyOrders
        /// </summary>
        [DataMember(Name="shipStationAllowScanningSKUToIdentifyOrders", EmitDefaultValue=false)]
        public bool? ShipStationAllowScanningSKUToIdentifyOrders { get; set; }

        /// <summary>
        /// Gets or Sets CreateDate
        /// </summary>
        [DataMember(Name="createDate", EmitDefaultValue=false)]
        public DateTime? CreateDate { get; private set; }

        /// <summary>
        /// Gets or Sets ModifyDate
        /// </summary>
        [DataMember(Name="modifyDate", EmitDefaultValue=false)]
        public DateTime? ModifyDate { get; private set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>
        [DataMember(Name="customFields", EmitDefaultValue=false)]
        public Dictionary<string, Object> CustomFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Warehouse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  _Client: ").Append(_Client).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  Street1: ").Append(Street1).Append("\n");
            sb.Append("  Street2: ").Append(Street2).Append("\n");
            sb.Append("  Street3: ").Append(Street3).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Zip: ").Append(Zip).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  LocationBarcodePrefix: ").Append(LocationBarcodePrefix).Append("\n");
            sb.Append("  LpnPrefix: ").Append(LpnPrefix).Append("\n");
            sb.Append("  TimeZone: ").Append(TimeZone).Append("\n");
            sb.Append("  PackStationAllowPackingBeforePickWorkIsComplete: ").Append(PackStationAllowPackingBeforePickWorkIsComplete).Append("\n");
            sb.Append("  PackStationSkipCartonLPN: ").Append(PackStationSkipCartonLPN).Append("\n");
            sb.Append("  PackStationRequireConfirmOnError: ").Append(PackStationRequireConfirmOnError).Append("\n");
            sb.Append("  PackStationAllowScanningSKUToIdentifyOrders: ").Append(PackStationAllowScanningSKUToIdentifyOrders).Append("\n");
            sb.Append("  PackStationAllowEntryOfItemQuantities: ").Append(PackStationAllowEntryOfItemQuantities).Append("\n");
            sb.Append("  ShipStationWeightCheckPackedOrders: ").Append(ShipStationWeightCheckPackedOrders).Append("\n");
            sb.Append("  ShipStationShowUserWeightCheckExceptions: ").Append(ShipStationShowUserWeightCheckExceptions).Append("\n");
            sb.Append("  ShipStationAutoPrintPreGeneratedLabels: ").Append(ShipStationAutoPrintPreGeneratedLabels).Append("\n");
            sb.Append("  ShipStationAllowScanningSKUToIdentifyOrders: ").Append(ShipStationAllowScanningSKUToIdentifyOrders).Append("\n");
            sb.Append("  CreateDate: ").Append(CreateDate).Append("\n");
            sb.Append("  ModifyDate: ").Append(ModifyDate).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Warehouse);
        }

        /// <summary>
        /// Returns true if Warehouse instances are equal
        /// </summary>
        /// <param name="input">Instance of Warehouse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Warehouse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this._Client == input._Client ||
                    (this._Client != null &&
                    this._Client.Equals(input._Client))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.Company == input.Company ||
                    (this.Company != null &&
                    this.Company.Equals(input.Company))
                ) && 
                (
                    this.Street1 == input.Street1 ||
                    (this.Street1 != null &&
                    this.Street1.Equals(input.Street1))
                ) && 
                (
                    this.Street2 == input.Street2 ||
                    (this.Street2 != null &&
                    this.Street2.Equals(input.Street2))
                ) && 
                (
                    this.Street3 == input.Street3 ||
                    (this.Street3 != null &&
                    this.Street3.Equals(input.Street3))
                ) && 
                (
                    this.City == input.City ||
                    (this.City != null &&
                    this.City.Equals(input.City))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.Zip == input.Zip ||
                    (this.Zip != null &&
                    this.Zip.Equals(input.Zip))
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.Phone == input.Phone ||
                    (this.Phone != null &&
                    this.Phone.Equals(input.Phone))
                ) && 
                (
                    this.LocationBarcodePrefix == input.LocationBarcodePrefix ||
                    (this.LocationBarcodePrefix != null &&
                    this.LocationBarcodePrefix.Equals(input.LocationBarcodePrefix))
                ) && 
                (
                    this.LpnPrefix == input.LpnPrefix ||
                    (this.LpnPrefix != null &&
                    this.LpnPrefix.Equals(input.LpnPrefix))
                ) && 
                (
                    this.TimeZone == input.TimeZone ||
                    (this.TimeZone != null &&
                    this.TimeZone.Equals(input.TimeZone))
                ) && 
                (
                    this.PackStationAllowPackingBeforePickWorkIsComplete == input.PackStationAllowPackingBeforePickWorkIsComplete ||
                    (this.PackStationAllowPackingBeforePickWorkIsComplete != null &&
                    this.PackStationAllowPackingBeforePickWorkIsComplete.Equals(input.PackStationAllowPackingBeforePickWorkIsComplete))
                ) && 
                (
                    this.PackStationSkipCartonLPN == input.PackStationSkipCartonLPN ||
                    (this.PackStationSkipCartonLPN != null &&
                    this.PackStationSkipCartonLPN.Equals(input.PackStationSkipCartonLPN))
                ) && 
                (
                    this.PackStationRequireConfirmOnError == input.PackStationRequireConfirmOnError ||
                    (this.PackStationRequireConfirmOnError != null &&
                    this.PackStationRequireConfirmOnError.Equals(input.PackStationRequireConfirmOnError))
                ) && 
                (
                    this.PackStationAllowScanningSKUToIdentifyOrders == input.PackStationAllowScanningSKUToIdentifyOrders ||
                    (this.PackStationAllowScanningSKUToIdentifyOrders != null &&
                    this.PackStationAllowScanningSKUToIdentifyOrders.Equals(input.PackStationAllowScanningSKUToIdentifyOrders))
                ) && 
                (
                    this.PackStationAllowEntryOfItemQuantities == input.PackStationAllowEntryOfItemQuantities ||
                    (this.PackStationAllowEntryOfItemQuantities != null &&
                    this.PackStationAllowEntryOfItemQuantities.Equals(input.PackStationAllowEntryOfItemQuantities))
                ) && 
                (
                    this.ShipStationWeightCheckPackedOrders == input.ShipStationWeightCheckPackedOrders ||
                    (this.ShipStationWeightCheckPackedOrders != null &&
                    this.ShipStationWeightCheckPackedOrders.Equals(input.ShipStationWeightCheckPackedOrders))
                ) && 
                (
                    this.ShipStationShowUserWeightCheckExceptions == input.ShipStationShowUserWeightCheckExceptions ||
                    (this.ShipStationShowUserWeightCheckExceptions != null &&
                    this.ShipStationShowUserWeightCheckExceptions.Equals(input.ShipStationShowUserWeightCheckExceptions))
                ) && 
                (
                    this.ShipStationAutoPrintPreGeneratedLabels == input.ShipStationAutoPrintPreGeneratedLabels ||
                    (this.ShipStationAutoPrintPreGeneratedLabels != null &&
                    this.ShipStationAutoPrintPreGeneratedLabels.Equals(input.ShipStationAutoPrintPreGeneratedLabels))
                ) && 
                (
                    this.ShipStationAllowScanningSKUToIdentifyOrders == input.ShipStationAllowScanningSKUToIdentifyOrders ||
                    (this.ShipStationAllowScanningSKUToIdentifyOrders != null &&
                    this.ShipStationAllowScanningSKUToIdentifyOrders.Equals(input.ShipStationAllowScanningSKUToIdentifyOrders))
                ) && 
                (
                    this.CreateDate == input.CreateDate ||
                    (this.CreateDate != null &&
                    this.CreateDate.Equals(input.CreateDate))
                ) && 
                (
                    this.ModifyDate == input.ModifyDate ||
                    (this.ModifyDate != null &&
                    this.ModifyDate.Equals(input.ModifyDate))
                ) && 
                (
                    this.CustomFields == input.CustomFields ||
                    this.CustomFields != null &&
                    this.CustomFields.SequenceEqual(input.CustomFields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this._Client != null)
                    hashCode = hashCode * 59 + this._Client.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.Company != null)
                    hashCode = hashCode * 59 + this.Company.GetHashCode();
                if (this.Street1 != null)
                    hashCode = hashCode * 59 + this.Street1.GetHashCode();
                if (this.Street2 != null)
                    hashCode = hashCode * 59 + this.Street2.GetHashCode();
                if (this.Street3 != null)
                    hashCode = hashCode * 59 + this.Street3.GetHashCode();
                if (this.City != null)
                    hashCode = hashCode * 59 + this.City.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.Zip != null)
                    hashCode = hashCode * 59 + this.Zip.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.Phone != null)
                    hashCode = hashCode * 59 + this.Phone.GetHashCode();
                if (this.LocationBarcodePrefix != null)
                    hashCode = hashCode * 59 + this.LocationBarcodePrefix.GetHashCode();
                if (this.LpnPrefix != null)
                    hashCode = hashCode * 59 + this.LpnPrefix.GetHashCode();
                if (this.TimeZone != null)
                    hashCode = hashCode * 59 + this.TimeZone.GetHashCode();
                if (this.PackStationAllowPackingBeforePickWorkIsComplete != null)
                    hashCode = hashCode * 59 + this.PackStationAllowPackingBeforePickWorkIsComplete.GetHashCode();
                if (this.PackStationSkipCartonLPN != null)
                    hashCode = hashCode * 59 + this.PackStationSkipCartonLPN.GetHashCode();
                if (this.PackStationRequireConfirmOnError != null)
                    hashCode = hashCode * 59 + this.PackStationRequireConfirmOnError.GetHashCode();
                if (this.PackStationAllowScanningSKUToIdentifyOrders != null)
                    hashCode = hashCode * 59 + this.PackStationAllowScanningSKUToIdentifyOrders.GetHashCode();
                if (this.PackStationAllowEntryOfItemQuantities != null)
                    hashCode = hashCode * 59 + this.PackStationAllowEntryOfItemQuantities.GetHashCode();
                if (this.ShipStationWeightCheckPackedOrders != null)
                    hashCode = hashCode * 59 + this.ShipStationWeightCheckPackedOrders.GetHashCode();
                if (this.ShipStationShowUserWeightCheckExceptions != null)
                    hashCode = hashCode * 59 + this.ShipStationShowUserWeightCheckExceptions.GetHashCode();
                if (this.ShipStationAutoPrintPreGeneratedLabels != null)
                    hashCode = hashCode * 59 + this.ShipStationAutoPrintPreGeneratedLabels.GetHashCode();
                if (this.ShipStationAllowScanningSKUToIdentifyOrders != null)
                    hashCode = hashCode * 59 + this.ShipStationAllowScanningSKUToIdentifyOrders.GetHashCode();
                if (this.CreateDate != null)
                    hashCode = hashCode * 59 + this.CreateDate.GetHashCode();
                if (this.ModifyDate != null)
                    hashCode = hashCode * 59 + this.ModifyDate.GetHashCode();
                if (this.CustomFields != null)
                    hashCode = hashCode * 59 + this.CustomFields.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
