/* 
 * Infoplus API
 *
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Infoplus.Client.SwaggerDateConverter;

namespace Infoplus.Model
{
    /// <summary>
    /// ZipCodeZone
    /// </summary>
    [DataContract]
    public partial class ZipCodeZone :  IEquatable<ZipCodeZone>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ZipCodeZone" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ZipCodeZone() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ZipCodeZone" /> class.
        /// </summary>
        /// <param name="WarehouseNo">WarehouseNo (required).</param>
        /// <param name="CarrierCompanyCode">CarrierCompanyCode (required).</param>
        /// <param name="Zip">Zip (required).</param>
        /// <param name="Zone">Zone (required).</param>
        /// <param name="CustomFields">CustomFields.</param>
        public ZipCodeZone(int? WarehouseNo = default(int?), string CarrierCompanyCode = default(string), string Zip = default(string), string Zone = default(string), Dictionary<string, Object> CustomFields = default(Dictionary<string, Object>))
        {
            // to ensure "WarehouseNo" is required (not null)
            if (WarehouseNo == null)
            {
                throw new InvalidDataException("WarehouseNo is a required property for ZipCodeZone and cannot be null");
            }
            else
            {
                this.WarehouseNo = WarehouseNo;
            }
            // to ensure "CarrierCompanyCode" is required (not null)
            if (CarrierCompanyCode == null)
            {
                throw new InvalidDataException("CarrierCompanyCode is a required property for ZipCodeZone and cannot be null");
            }
            else
            {
                this.CarrierCompanyCode = CarrierCompanyCode;
            }
            // to ensure "Zip" is required (not null)
            if (Zip == null)
            {
                throw new InvalidDataException("Zip is a required property for ZipCodeZone and cannot be null");
            }
            else
            {
                this.Zip = Zip;
            }
            // to ensure "Zone" is required (not null)
            if (Zone == null)
            {
                throw new InvalidDataException("Zone is a required property for ZipCodeZone and cannot be null");
            }
            else
            {
                this.Zone = Zone;
            }
            this.CustomFields = CustomFields;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int? Id { get; private set; }

        /// <summary>
        /// Gets or Sets CreateDate
        /// </summary>
        [DataMember(Name="createDate", EmitDefaultValue=false)]
        public DateTime? CreateDate { get; private set; }

        /// <summary>
        /// Gets or Sets ModifyDate
        /// </summary>
        [DataMember(Name="modifyDate", EmitDefaultValue=false)]
        public DateTime? ModifyDate { get; private set; }

        /// <summary>
        /// Gets or Sets WarehouseNo
        /// </summary>
        [DataMember(Name="warehouseNo", EmitDefaultValue=false)]
        public int? WarehouseNo { get; set; }

        /// <summary>
        /// Gets or Sets CarrierCompanyCode
        /// </summary>
        [DataMember(Name="carrierCompanyCode", EmitDefaultValue=false)]
        public string CarrierCompanyCode { get; set; }

        /// <summary>
        /// Gets or Sets Zip
        /// </summary>
        [DataMember(Name="zip", EmitDefaultValue=false)]
        public string Zip { get; set; }

        /// <summary>
        /// Gets or Sets Zone
        /// </summary>
        [DataMember(Name="zone", EmitDefaultValue=false)]
        public string Zone { get; set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>
        [DataMember(Name="customFields", EmitDefaultValue=false)]
        public Dictionary<string, Object> CustomFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ZipCodeZone {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreateDate: ").Append(CreateDate).Append("\n");
            sb.Append("  ModifyDate: ").Append(ModifyDate).Append("\n");
            sb.Append("  WarehouseNo: ").Append(WarehouseNo).Append("\n");
            sb.Append("  CarrierCompanyCode: ").Append(CarrierCompanyCode).Append("\n");
            sb.Append("  Zip: ").Append(Zip).Append("\n");
            sb.Append("  Zone: ").Append(Zone).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ZipCodeZone);
        }

        /// <summary>
        /// Returns true if ZipCodeZone instances are equal
        /// </summary>
        /// <param name="input">Instance of ZipCodeZone to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ZipCodeZone input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.CreateDate == input.CreateDate ||
                    (this.CreateDate != null &&
                    this.CreateDate.Equals(input.CreateDate))
                ) && 
                (
                    this.ModifyDate == input.ModifyDate ||
                    (this.ModifyDate != null &&
                    this.ModifyDate.Equals(input.ModifyDate))
                ) && 
                (
                    this.WarehouseNo == input.WarehouseNo ||
                    (this.WarehouseNo != null &&
                    this.WarehouseNo.Equals(input.WarehouseNo))
                ) && 
                (
                    this.CarrierCompanyCode == input.CarrierCompanyCode ||
                    (this.CarrierCompanyCode != null &&
                    this.CarrierCompanyCode.Equals(input.CarrierCompanyCode))
                ) && 
                (
                    this.Zip == input.Zip ||
                    (this.Zip != null &&
                    this.Zip.Equals(input.Zip))
                ) && 
                (
                    this.Zone == input.Zone ||
                    (this.Zone != null &&
                    this.Zone.Equals(input.Zone))
                ) && 
                (
                    this.CustomFields == input.CustomFields ||
                    this.CustomFields != null &&
                    this.CustomFields.SequenceEqual(input.CustomFields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.CreateDate != null)
                    hashCode = hashCode * 59 + this.CreateDate.GetHashCode();
                if (this.ModifyDate != null)
                    hashCode = hashCode * 59 + this.ModifyDate.GetHashCode();
                if (this.WarehouseNo != null)
                    hashCode = hashCode * 59 + this.WarehouseNo.GetHashCode();
                if (this.CarrierCompanyCode != null)
                    hashCode = hashCode * 59 + this.CarrierCompanyCode.GetHashCode();
                if (this.Zip != null)
                    hashCode = hashCode * 59 + this.Zip.GetHashCode();
                if (this.Zone != null)
                    hashCode = hashCode * 59 + this.Zone.GetHashCode();
                if (this.CustomFields != null)
                    hashCode = hashCode * 59 + this.CustomFields.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
